import { BadmintonTest } from "@/types/assessment.types";

export const BADMINTON_TESTS: BadmintonTest[] = [
  // ================= U9 =================
  {
    id: "u9_keep_uppy",
    ageGroup: "U9",
    name: "Жонглиране с перо (Keep-uppy)",
    source: "BWF Shuttle Time (Lesson 3)",
    description:
      "Детето трябва да удря перото нагоре с ракетата (форхенд хват), без да го изпуска на земята. Време за опит: 30 секунди.",
    equipment: "1 ракета, 1 перо на дете.",
    scoring: "Брой успешни последователни удара без падане (Макс: 30).",
    focus: "Координация око-ръка, усет към ракетата.",
    maxScore: 30,
    scoreUnit: "бр.",
    scoreType: "number",
  },
  {
    id: "u9_catch",
    ageGroup: "U9",
    name: "Хвърляне и хващане",
    source: "BWF Level 1",
    description:
      "Треньорът хвърля перо от другата страна на мрежата. Детето трябва да се придвижи и да го хване с ръка ПРЕДИ да падне.",
    equipment: "Мрежа, кош с пера.",
    scoring: "10 опита. 1 точка за всяко хванато перо.",
    focus: "Бързина, реакция, работа с крака (придвижване напред).",
    maxScore: 10,
    scoreUnit: "т.",
    scoreType: "number",
  },
  {
    id: "u9_hanging_shuttle",
    ageGroup: "U9",
    name: "Удар по висящо перо",
    source: "BWF Shuttle Time",
    description:
      "Удряне на перо, окачено на връв над детето. Детето се позиционира и изпълнява удар над глава (overhead).",
    equipment: "Връв, окачено перо, ракета.",
    scoring:
      "10 опита. Оценява се таймингът и контактът с перото (от 0 до 10 точни удара).",
    focus: "Тайминг, усет за дистанция, начална overhead техника.",
    maxScore: 10,
    scoreUnit: "т.",
    scoreType: "number",
  },
  {
    id: "u9_agility_run",
    ageGroup: "U9",
    name: "Бягане със смяна на посоката",
    source: "BWF Coach Education",
    description:
      "Спринт между конуси (или линиите на корта за единично) - напред, назад и настрани, докосвайки пода.",
    equipment: "Конуси или линиите на корта, хронометър.",
    scoring: "Време за завършване на маршрута (по-ниското е по-добро).",
    focus: "Бързина, ловкост и смяна на посоката.",
    scoreUnit: "сек.",
    scoreType: "time",
  },
  {
    id: "u9_short_serve_target",
    ageGroup: "U9",
    name: "Къс сервис в цел (базово)",
    source: "BWF Shuttle Time",
    description:
      "Детето изпълнява 10 сервиса (форхенд или бекхенд) с цел перото да падне в предната сервис зона.",
    equipment: "Мрежа, пера, обръч или маркер в предната зона.",
    scoring: "Брой пера, попаднали в обръча/зоната (от 10).",
    focus: "Контрол на силата, насочване.",
    maxScore: 10,
    scoreUnit: "т.",
    scoreType: "number",
  },

  // ================= U11 =================
  {
    id: "u11_backhand_serve",
    ageGroup: "U11",
    name: "Къс бекхенд сервис",
    source: "BWF Level 1",
    description:
      "Изпълнение на къс бекхенд сервис. Перото трябва да премине ниско над мрежата и да падне в предната сервис зона (или в цел).",
    equipment: "Маркери в предната сервис зона. Обръч за цел.",
    scoring: "10 опита. 1 т. за правилен сервиз, 2 т. ако попадне в обръча.",
    focus: "Точност, биомеханика на бекхенд сервис.",
    maxScore: 20,
    scoreUnit: "т.",
    scoreType: "number",
  },
  {
    id: "u11_star_footwork",
    ageGroup: "U11",
    name: 'Движение "Звезда" (Footwork)',
    source: "Badminton Europe",
    description:
      "Детето стартира от центъра. При сигнал докосва 4-те ъгъла на корта последователно, връщайки се в центъра (split-step) след всеки.",
    equipment: "Корт за единично, хронометър.",
    scoring: "Време за завършване на 1 пълен цикъл.",
    focus: "Специфична бадминтон пъргавина, split-step.",
    scoreUnit: "сек.",
    scoreType: "time",
  },
  {
    id: "u11_forehand_clear",
    ageGroup: "U11",
    name: "Форхенд клиър",
    source: "BWF Level 1",
    description:
      "Треньорът подава пера. Детето изпълнява форхенд клиър. Перото трябва да падне между задната сервис линия за двойки и основната линия.",
    equipment: "Корт, пера, маркирана задна зона.",
    scoring: "10 опита. Точки за брой пера, паднали в целевата зона.",
    focus: "Тайминг, завъртане на тялото, дистанция.",
    maxScore: 10,
    scoreUnit: "т.",
    scoreType: "number",
  },
  {
    id: "u11_wall_drive",
    ageGroup: "U11",
    name: "Повтаряеми удари до стена (Drive)",
    source: "BWF Coach Education",
    description:
      "Детето изпълнява плоски удари (drives) срещу стена от разстояние 2-3 метра.",
    equipment: "Гладка стена, ракета, перо.",
    scoring: "Брой успешни последователни удара за 30 секунди.",
    focus: "Реакция, смяна на хват (форхенд/бекхенд), скорост на ръката.",
    scoreUnit: "бр.",
    scoreType: "number",
  },
  {
    id: "u11_med_ball_throw",
    ageGroup: "U11",
    name: "Хвърляне на медицинска топка",
    source: "Национални методики",
    description:
      "Детето застава с двата крака успоредно и хвърля 1 кг медицинска топка над глава (имитация на движението при клиър/смеш).",
    equipment: "Медицинска топка (1 кг), рулетка.",
    scoring: "Дистанция в метри (най-добър от 3 опита).",
    focus: "Експлозивна сила на горната част на тялото и коремната преса.",
    scoreUnit: "м.",
    scoreType: "number", // we can parse floats
  },

  // ================= U13 =================
  {
    id: "u13_high_clear",
    ageGroup: "U13",
    name: "Дълъг форхенд сервис (High Clear)",
    source: "BWF Level 2",
    description:
      "Сервисът трябва да бъде изпратен високо и да падне в най-задната линия на корта. Перото трябва да мине над определена височина.",
    equipment: "Въже над мрежата (опционално), маркери отзад.",
    scoring: "10 опита. 1 т. за дистанция, 2 т. за дистанция + височина.",
    focus: "Мощност, тайминг, трансфер на тежестта.",
    maxScore: 20,
    scoreUnit: "т.",
    scoreType: "number",
  },
  {
    id: "u13_rear_drop_shot",
    ageGroup: "U13",
    name: "Дроп шот от задна линия",
    source: "Badminton Asia",
    description:
      "Треньорът подава високо перо назад. Детето изпълнява дроп шот (форхенд) пред линията за къс сервис.",
    equipment:
      "Треньор за подаване, маркери в предна зона (зони 1, 2, 3 точки).",
    scoring:
      "10 опита. Оценява се точността и близостта до мрежата (макс 30 т.).",
    focus: "Техника над глава, прецизност и скриване на удара.",
    maxScore: 30,
    scoreUnit: "т.",
    scoreType: "number",
  },
  {
    id: "u13_net_spin",
    ageGroup: "U13",
    name: "Мрежова игра (Net spin)",
    source: "BWF Level 2",
    description:
      "Подаване на пера близо до мрежата. Детето изпълнява мрежов удар с цел перото да се завърти (tumble) и да падне максимално близо.",
    equipment: "Мрежа, кош с пера.",
    scoring:
      "10 опита (5 форхенд, 5 бекхенд). Точки за качество на завъртането и близост.",
    focus: "Фин контрол с пръсти, усет, позиция на ракетата.",
    maxScore: 10,
    scoreUnit: "т.",
    scoreType: "number",
  },
  {
    id: "u13_6_point_footwork",
    ageGroup: "U13",
    name: "Footwork: 6 ъгъла",
    source: "Badminton Europe",
    description:
      "Shadow badminton движение към 6-те точки на корта (2 отпред, 2 отстрани, 2 отзад) и връщане в центъра.",
    equipment: "Корт за единично, хронометър.",
    scoring: "Време за изпълнение на 2 пълни цикъла (12 докосвания).",
    focus: "Издръжливост в скоростта, ефикасност на стъпките.",
    scoreUnit: "сек.",
    scoreType: "time",
  },
  {
    id: "u13_smash_speed",
    ageGroup: "U13",
    name: "Забиване (Smash) от място",
    source: "BWF Coach Education",
    description:
      "Изпълнение на форхенд смеш от средната част на корта. Ако има радар - мери се скорост. Иначе се оценява точност в 2 целеви зони отстрани.",
    equipment: "Радар или целеви зони на корта.",
    scoring: "Най-висока скорост (km/h) ИЛИ брой успешни попадения от 10.",
    focus: "Експлозивност, биомеханична верига.",
    scoreUnit: "km/h / т.",
    scoreType: "number",
  },

  // ================= U15 =================
  {
    id: "u15_jump_smash",
    ageGroup: "U15",
    name: "Смеш в движение (Jump Smash)",
    source: "BWF Level 2",
    description:
      "Детето се изнася назад от центъра, скача и забива от висока точка. Изпълняват се 10 опита.",
    equipment: "Треньор за подаване (многокартно).",
    scoring: "Успеваемост: брой мощни удари в очертанията (от 10).",
    focus: "Тайминг на отскока, координация във въздуха, сила.",
    maxScore: 10,
    scoreUnit: "т.",
    scoreType: "number",
  },
  {
    id: "u15_smash_defense",
    ageGroup: "U15",
    name: "Защита от смеш",
    source: "Badminton Asia",
    description:
      "Треньорът (или по-голям играч) забива към защитника. Защитникът трябва да блокира перото в целева зона близо до мрежата.",
    equipment: "Маркери в предна зона.",
    scoring: "10 опита. Брой успешни, контролирани блокове.",
    focus: "Рефлекси, нисък център на тежестта, мек хват.",
    maxScore: 10,
    scoreUnit: "т.",
    scoreType: "number",
  },
  {
    id: "u15_shuttle_run",
    ageGroup: "U15",
    name: 'Тест "Совалка" (Shuttle Run)',
    source: "Спортна физиология",
    description:
      "Тичане между двете странични линии (или 10 метра). Докосване на линията с ръка.",
    equipment: "Метър/Линии, хронометър.",
    scoring: "Брой отсечки за 1 минута.",
    focus: "Анаеробна издръжливост, бърза смяна на посоката.",
    scoreUnit: "бр.",
    scoreType: "number",
  },
  {
    id: "u15_cross_drop",
    ageGroup: "U15",
    name: "Крос-корт дроп шот",
    source: "BWF Level 2",
    description: "От заден десен ъгъл към преден ляв ъгъл (и обратно).",
    equipment: "Мишени в предните ъгли.",
    scoring: "10 опита по диагонал. Точкува се прецизността (1-3 т.).",
    focus: "Контрол на ъгъла на ракетата, трудна траектория.",
    maxScore: 30,
    scoreUnit: "т.",
    scoreType: "number",
  },
  {
    id: "u15_multi_feed_20",
    ageGroup: "U15",
    name: "Мулти-фийд Издръжливост (20 пера)",
    source: "BWF Coach Education",
    description:
      "Треньорът подава 20 пера в различни ъгли с високо темпо (1 перо на секунда). Играчът трябва да върне всяко.",
    equipment: "Кош с пера.",
    scoring: "Време до изпускане на темпото или брой успешно върнати пера.",
    focus: "Издръжливост под напрежение, възстановяване на позиция.",
    maxScore: 20,
    scoreUnit: "бр.",
    scoreType: "number",
  },

  // ================= U17 =================
  {
    id: "u17_attacking_clear",
    ageGroup: "U17",
    name: "Атакуващ клиър (Attacking Clear)",
    source: "BWF Level 3",
    description:
      "Бърз, плосък клиър, който преминава точно над обсега на противника и пада бързо в задната зона.",
    equipment: "Маркери в задна зона.",
    scoring: "10 опита. Оценява се траекторията и скоростта.",
    focus: "Изненадваща атака, агресивно позициониране.",
    maxScore: 10,
    scoreUnit: "т.",
    scoreType: "number",
  },
  {
    id: "u17_defense_counter",
    ageGroup: "U17",
    name: "Защита с контраатака (Drive defense)",
    source: "Badminton Europe",
    description:
      "Защита на смеш чрез бърз drive удар в тялото/свободната зона на нападателя.",
    equipment: "Треньор забива.",
    scoring: "Брой успешни контраатаки от 10 смеша.",
    focus: "Преход от защита в атака, нападателен бекхенд.",
    maxScore: 10,
    scoreUnit: "т.",
    scoreType: "number",
  },
  {
    id: "u17_beep_test",
    ageGroup: "U17",
    name: "BWF Beep Test (Bleep Test)",
    source: "Стандартна физиология",
    description:
      "Многостепенен фитнес тест за аеробна издръжливост с прогресивно увеличаващо се темпо.",
    equipment: "Аудио запис за Beep Test, 20 метра разстояние.",
    scoring:
      "Ниво (Level) и совалка (Shuttle), до което е достигнал състезателят (напр. 10.4).",
    focus: "VO2 Max, максимална аеробна издръжливост.",
    scoreUnit: "Ниво",
    scoreType: "number",
  },
  {
    id: "u17_deceptive_drop",
    ageGroup: "U17",
    name: "Измамни удари (Deceptive drop)",
    source: "BWF Level 3",
    description:
      "Подготовка за силен клиър/смеш, последвана от забавяне (slice/reverse slice) за дроп шот.",
    equipment: "Мишени отпред.",
    scoring: "10 опита. Оценява се качеството на измамата и точността.",
    focus: "Забавяне на ракетата, движение на китката.",
    maxScore: 10,
    scoreUnit: "т.",
    scoreType: "number",
  },
  {
    id: "u17_shadow_1min",
    ageGroup: "U17",
    name: "Shadow Badminton (1 минута макс)",
    source: "Национални федерации",
    description:
      "Движение по корта без перо на 100% интензитет. Треньорът показва посоките (random feed).",
    equipment: "Треньор, хронометър.",
    scoring:
      "Оценява се поддържането на правилна техника в последните 15 секунди (Скала 1-10).",
    focus: "Лактатна толерантност, поддържане на техника при умора.",
    maxScore: 10,
    scoreUnit: "т.",
    scoreType: "number",
  },

  // ================= U19 =================
  {
    id: "u19_vertical_jump",
    ageGroup: "U19",
    name: "Тест за експлозивна сила (Vertical Jump)",
    source: "Спортна физиология",
    description: "Измерване на вертикалния отскок от място с изпъната ръка.",
    equipment: "Стена с метър или Vertec система.",
    scoring: "Височина на отскока в сантиметри.",
    focus: "Експлозивна сила на краката (за Jump Smash).",
    scoreUnit: "см.",
    scoreType: "number",
  },
  {
    id: "u19_fatigue_accuracy",
    ageGroup: "U19",
    name: "Точност под умора",
    source: "BWF Level 3",
    description:
      "След 30 секунди интензивен Shadow footwork, състезателят трябва да изпълни 5 прецизни удара по мишени.",
    equipment: "Мишени.",
    scoring: "Брой точни попадения (от 5).",
    focus: "Концентрация и моторно управление при висок пулс.",
    maxScore: 5,
    scoreUnit: "т.",
    scoreType: "number",
  },
  {
    id: "u19_smash_defense_series",
    ageGroup: "U19",
    name: "Смеш защита в серия (30 пера)",
    source: "Badminton Asia",
    description:
      "Двама подавачи забиват последователно 30 пера към състезателя без пауза.",
    equipment: "Двама забиващи, много пера.",
    scoring: "Брой върнати пера в очертанията.",
    focus: "Издръжливост в защита, бързина на реакциите.",
    maxScore: 30,
    scoreUnit: "бр.",
    scoreType: "number",
  },
  {
    id: "u19_drive_battle",
    ageGroup: "U19",
    name: "Двойки: Плоска игра (Drive battle)",
    source: "BWF Doubles Specific",
    description:
      "Двама състезатели играят бързи drives един срещу друг в предната 1/2 на корта.",
    equipment: "Корт, перо.",
    scoring:
      "Брой преминавания на перото над мрежата за 30 секунди без грешка.",
    focus: "Реакция, късо движение, хват.",
    scoreUnit: "бр.",
    scoreType: "number",
  },
  {
    id: "u19_match_serve",
    ageGroup: "U19",
    name: "Сервис под напрежение (20-20)",
    source: "Психологическа подготовка",
    description:
      "Изпълнение на сервис при симулирана ситуация на мач-пойнт (напр. със звуково смущение или физическо натоварване преди това).",
    equipment: "Корт.",
    scoring: "Процент успешност от 10 опита (целева зона).",
    focus: "Психологическа устойчивост, рутина.",
    maxScore: 10,
    scoreUnit: "т.",
    scoreType: "number",
  },

  // ================= Мъже и Жени =================
  {
    id: "adult_1rm_squat",
    ageGroup: "Мъже и Жени",
    name: "1RM Клек (Squat)",
    source: "Кондиционна подготовка",
    description:
      "Максимална тежест за едно повторение на клек с щанга (с правилна форма).",
    equipment: "Щанга, тежести.",
    scoring: "Вдигнати килограми.",
    focus: "Абсолютна сила на долната част на тялото.",
    scoreUnit: "кг.",
    scoreType: "number",
  },
  {
    id: "adult_smash_power_acc",
    ageGroup: "Мъже и Жени",
    name: "Смеш: Сила и Точност",
    source: "BWF High Performance",
    description:
      "Изпълнение на Jump Smash с максимална сила към мишена 30x30 см на страничната линия.",
    equipment: "Мишени 30x30 см.",
    scoring: "Брой попадения от 10 удара при поддържане на максимална сила.",
    focus:
      "Peak performance - пресечна точка между експлозивност и микро-точност.",
    maxScore: 10,
    scoreUnit: "т.",
    scoreType: "number",
  },
  {
    id: "adult_anaerobic_3min",
    ageGroup: "Мъже и Жени",
    name: "Анаеробна Издръжливост (3 мин)",
    source: "BWF High Performance",
    description:
      "Непрекъснато подаване на пера (multi-feed) във всички краища на корта за 3 минути (приблизителна дължина на много тежко разиграване).",
    equipment: "Треньор, 300+ пера.",
    scoring:
      "Измерване на спада в качеството на ударите през последната минута.",
    focus: "Екстремна лактатна толерантност.",
    scoreUnit: "% спад",
    scoreType: "number",
  },
  {
    id: "adult_tactical_recovery",
    ageGroup: "Мъже и Жени",
    name: "Тактическо възстановяване",
    source: "Badminton Europe",
    description:
      "Старт от позиция легнал по гръб. При сигнал играчът се изправя, отразява тежък удар в ъгъла и се връща в центъра.",
    equipment: "Хронометър, треньор.",
    scoring: "Време за реакция и връщане в позиция.",
    focus: "Възстановяване след загуба на баланс (dive).",
    scoreUnit: "сек.",
    scoreType: "time",
  },
  {
    id: "adult_decision_making",
    ageGroup: "Мъже и Жени",
    name: "Вземане на решения под стрес",
    source: "Когнитивна спортна психология",
    description:
      "Треньорът подава перо и в същия момент извиква цвят. Играчът трябва да изпълни специфичен удар, съответстващ на цвета.",
    equipment: "Кош с пера.",
    scoring: "Процент правилни решения (от 20).",
    focus: "Когнитивна обработка под физически стрес.",
    maxScore: 20,
    scoreUnit: "т.",
    scoreType: "number",
  },
];
