import { BadmintonTest } from "@/types/assessment.types";

export const BADMINTON_TESTS: BadmintonTest[] = [
  // ================= U9 =================
  {
    id: "u9_keep_uppy",
    ageGroup: "U9",
    name: "Жонглиране с перо (Keep-uppy)",
    source: "BWF Shuttle Time (Lesson 3)",
    description:
      "Детето трябва да удря перото нагоре с ракетата (форхенд хват), без да го изпуска на земята. Време за опит: 30 секунди.",
    equipment: "1 ракета, 1 перо на дете.",
    scoring: "Брой успешни последователни удара без падане (Макс: 30).",
    focus: "Координация око-ръка, усет към ракетата.",
    maxScore: 30,
    scoreUnit: "бр.",
    scoreType: "number",
  },
  {
    id: "u9_catch",
    ageGroup: "U9",
    name: "Хвърляне и хващане",
    source: "BWF Level 1",
    description:
      "Треньорът хвърля перо от другата страна на мрежата. Детето трябва да се придвижи и да го хване с ръка ПРЕДИ да падне.",
    equipment: "Мрежа, кош с пера.",
    scoring: "10 опита. 1 точка за всяко хванато перо.",
    focus: "Бързина, реакция, работа с крака (придвижване напред).",
    maxScore: 10,
    scoreUnit: "т.",
    scoreType: "number",
  },
  {
    id: "u9_hanging_shuttle",
    ageGroup: "U9",
    name: "Удар по висящо перо",
    source: "BWF Shuttle Time",
    description:
      "Удряне на перо, окачено на връв над детето. Детето се позиционира и изпълнява удар над глава (overhead).",
    equipment: "Връв, окачено перо, ракета.",
    scoring:
      "10 опита. Оценява се таймингът и контактът с перото (от 0 до 10 точни удара).",
    focus: "Тайминг, усет за дистанция, начална overhead техника.",
    maxScore: 10,
    scoreUnit: "т.",
    scoreType: "number",
  },
  {
    id: "u9_agility_run",
    ageGroup: "U9",
    name: "Бягане със смяна на посоката",
    source: "BWF Coach Education",
    description:
      "Спринт между конуси (или линиите на корта за единично) - напред, назад и настрани, докосвайки пода.",
    equipment: "Конуси или линиите на корта, хронометър.",
    scoring: "Време за завършване на маршрута (по-ниското е по-добро).",
    focus: "Бързина, ловкост и смяна на посоката.",
    scoreUnit: "сек.",
    scoreType: "time",
  },
  {
    id: "u9_short_serve_target",
    ageGroup: "U9",
    name: "Къс сервис в цел (базово)",
    source: "BWF Shuttle Time",
    description:
      "Детето изпълнява 10 сервиса (форхенд или бекхенд) с цел перото да падне в предната сервис зона.",
    equipment: "Мрежа, пера, обръч или маркер в предната зона.",
    scoring: "Брой пера, попаднали в обръча/зоната (от 10).",
    focus: "Контрол на силата, насочване.",
    maxScore: 10,
    scoreUnit: "т.",
    scoreType: "number",
  },
  {
    id: "u9_racket_pack_balance",
    ageGroup: "U9",
    name: "Баланс на перо (The Racket Pack)",
    source: "Badminton England",
    description:
      "Детето трябва да балансира перо върху кордажа на ракетата си и да премине разстояние от 5 метра без да го изпусне.",
    equipment: "Ракета, перо, конуси за отбелязване на 5 метра.",
    scoring: "Време за преминаване. Ако изпусне перото, започва отначало.",
    focus: "Баланс, фокус, правилен форхенд хват.",
    scoreUnit: "сек.",
    scoreType: "time",
  },
  {
    id: "u9_balloon_taps",
    ageGroup: "U9",
    name: "Контрол с балон",
    source: "BWF Shuttle Time",
    description:
      "Удряне на балон с ракетата нагоре. Балонът пада по-бавно, което дава време на детето да се позиционира правилно под него.",
    equipment: "Надут балон, ракета.",
    scoring: "Брой успешни удари за 1 минута.",
    focus: "Тайминг, визуално проследяване, позициониране на краката.",
    scoreUnit: "бр.",
    scoreType: "number",
  },
  {
    id: "u9_maze_run",
    ageGroup: "U9",
    name: "Лабиринт по линиите",
    source: "Badminton Europe",
    description:
      "Детето трябва да се придвижва само по линиите на корта възможно най-бързо от единия край до другия, имитирайки бадминтон стъпки.",
    equipment: "Корт, хронометър.",
    scoring: "Време за преминаване на маршрута.",
    focus: "Ориентация в пространството, познаване на корта.",
    scoreUnit: "сек.",
    scoreType: "time",
  },
  {
    id: "u9_target_throw",
    ageGroup: "U9",
    name: "Хвърляне на малка топка в цел",
    source: "Национални методики",
    description:
      "Хвърляне на тенис топка или перо с ръка (движение като при клиър/смеш) към мишена на стената или пода.",
    equipment: "Малки топки, мишена.",
    scoring: "Брой точни попадения от 10 опита.",
    focus: "Биомеханика на хвърлянето, пренос на тежестта.",
    maxScore: 10,
    scoreUnit: "т.",
    scoreType: "number",
  },

  // ================= U11 =================
  {
    id: "u11_backhand_serve",
    ageGroup: "U11",
    name: "Къс бекхенд сервис",
    source: "BWF Level 1",
    description:
      "Изпълнение на къс бекхенд сервис. Перото трябва да премине ниско над мрежата и да падне в предната сервис зона (или в цел).",
    equipment: "Маркери в предната сервис зона. Обръч за цел.",
    scoring: "10 опита. 1 т. за правилен сервиз, 2 т. ако попадне в обръча.",
    focus: "Точност, биомеханика на бекхенд сервис.",
    maxScore: 20,
    scoreUnit: "т.",
    scoreType: "number",
  },
  {
    id: "u11_star_footwork",
    ageGroup: "U11",
    name: 'Движение "Звезда" (Footwork)',
    source: "Badminton Europe",
    description:
      "Детето стартира от центъра. При сигнал докосва 4-те ъгъла на корта последователно, връщайки се в центъра (split-step) след всеки.",
    equipment: "Корт за единично, хронометър.",
    scoring: "Време за завършване на 1 пълен цикъл.",
    focus: "Специфична бадминтон пъргавина, split-step.",
    scoreUnit: "сек.",
    scoreType: "time",
  },
  {
    id: "u11_forehand_clear",
    ageGroup: "U11",
    name: "Форхенд клиър",
    source: "BWF Level 1",
    description:
      "Треньорът подава пера. Детето изпълнява форхенд клиър. Перото трябва да падне между задната сервис линия за двойки и основната линия.",
    equipment: "Корт, пера, маркирана задна зона.",
    scoring: "10 опита. Точки за брой пера, паднали в целевата зона.",
    focus: "Тайминг, завъртане на тялото, дистанция.",
    maxScore: 10,
    scoreUnit: "т.",
    scoreType: "number",
  },
  {
    id: "u11_wall_drive",
    ageGroup: "U11",
    name: "Повтаряеми удари до стена (Drive)",
    source: "BWF Coach Education",
    description:
      "Детето изпълнява плоски удари (drives) срещу стена от разстояние 2-3 метра.",
    equipment: "Гладка стена, ракета, перо.",
    scoring: "Брой успешни последователни удара за 30 секунди.",
    focus: "Реакция, смяна на хват (форхенд/бекхенд), скорост на ръката.",
    scoreUnit: "бр.",
    scoreType: "number",
  },
  {
    id: "u11_med_ball_throw",
    ageGroup: "U11",
    name: "Хвърляне на медицинска топка",
    source: "Национални методики",
    description:
      "Детето застава с двата крака успоредно и хвърля 1 кг медицинска топка над глава (имитация на движението при клиър/смеш).",
    equipment: "Медицинска топка (1 кг), рулетка.",
    scoring: "Дистанция в метри (най-добър от 3 опита).",
    focus: "Експлозивна сила на горната част на тялото и коремната преса.",
    scoreUnit: "м.",
    scoreType: "number",
  },
  {
    id: "u11_scissor_jump",
    ageGroup: "U11",
    name: "Ножичен отскок (Scissor Jump)",
    source: "Badminton Denmark",
    description:
      "Имитация на ножичен отскок за задна зона (смяна на краката във въздуха), изпълнена на място без ракета.",
    equipment: "Няма.",
    scoring: "Оценка от 1 до 10 за правилната биомеханика и ротация на таза.",
    focus: "Координация на долната част на тялото, подготовка за смеш.",
    maxScore: 10,
    scoreUnit: "т.",
    scoreType: "number",
  },
  {
    id: "u11_underhand_wall",
    ageGroup: "U11",
    name: "Защита до стена (Underhand)",
    source: "BWF Shuttle Time",
    description:
      "Детето стои на 1.5 метра от стената и изпълнява удари отдолу (underhand), поддържайки перото в игра.",
    equipment: "Гладка стена, ракета, перо.",
    scoring: "Брой последователни удари.",
    focus: "Реакция при защита, контрол на силата.",
    scoreUnit: "бр.",
    scoreType: "number",
  },
  {
    id: "u11_sponge_defense",
    ageGroup: "U11",
    name: "Защита с гъба",
    source: "Badminton Denmark",
    description:
      "Треньорът хвърля леки топки/гъби. Детето трябва да ги блокира с ракетата (като при защита), омекотявайки удара.",
    equipment: "Меки топки или дунапренени гъби.",
    scoring: "Брой успешно омекотени топки, които падат близо до мрежата.",
    focus: "Мек хват, абсорбиране на силата.",
    maxScore: 10,
    scoreUnit: "т.",
    scoreType: "number",
  },
  {
    id: "u11_drive_rally",
    ageGroup: "U11",
    name: "Drive рали през мрежа",
    source: "BWF Level 1",
    description:
      "Две деца си подават плоски удари през мрежата от средата на корта.",
    equipment: "Мрежа, ракети, пера.",
    scoring: "Брой последователни удари без грешка.",
    focus: "Контрол на височината и силата, подготовка на ракетата.",
    scoreUnit: "бр.",
    scoreType: "number",
  },

  // ================= U13 =================
  {
    id: "u13_high_clear",
    ageGroup: "U13",
    name: "Дълъг форхенд сервис (High Clear)",
    source: "BWF Level 2",
    description:
      "Сервисът трябва да бъде изпратен високо и да падне в най-задната линия на корта. Перото трябва да мине над определена височина.",
    equipment: "Въже над мрежата (опционално), маркери отзад.",
    scoring: "10 опита. 1 т. за дистанция, 2 т. за дистанция + височина.",
    focus: "Мощност, тайминг, трансфер на тежестта.",
    maxScore: 20,
    scoreUnit: "т.",
    scoreType: "number",
  },
  {
    id: "u13_rear_drop_shot",
    ageGroup: "U13",
    name: "Дроп шот от задна линия",
    source: "Badminton Asia",
    description:
      "Треньорът подава високо перо назад. Детето изпълнява дроп шот (форхенд) пред линията за къс сервис.",
    equipment: "Треньор за подаване, маркери в предна зона.",
    scoring:
      "10 опита. Оценява се точността и близостта до мрежата (макс 30 т.).",
    focus: "Техника над глава, прецизност и скриване на удара.",
    maxScore: 30,
    scoreUnit: "т.",
    scoreType: "number",
  },
  {
    id: "u13_net_spin",
    ageGroup: "U13",
    name: "Мрежова игра (Net spin)",
    source: "BWF Level 2",
    description:
      "Подаване на пера близо до мрежата. Детето изпълнява мрежов удар с цел перото да се завърти (tumble) и да падне максимално близо.",
    equipment: "Мрежа, кош с пера.",
    scoring:
      "10 опита (5 форхенд, 5 бекхенд). Точки за качество на завъртането.",
    focus: "Фин контрол с пръсти, усет, позиция на ракетата.",
    maxScore: 10,
    scoreUnit: "т.",
    scoreType: "number",
  },
  {
    id: "u13_6_point_footwork",
    ageGroup: "U13",
    name: "Footwork: 6 ъгъла",
    source: "Badminton Europe",
    description:
      "Shadow badminton движение към 6-те точки на корта (2 отпред, 2 отстрани, 2 отзад) и връщане в центъра.",
    equipment: "Корт за единично, хронометър.",
    scoring: "Време за изпълнение на 2 пълни цикъла (12 докосвания).",
    focus: "Издръжливост в скоростта, ефикасност на стъпките.",
    scoreUnit: "сек.",
    scoreType: "time",
  },
  {
    id: "u13_smash_speed",
    ageGroup: "U13",
    name: "Забиване (Smash) от място",
    source: "BWF Coach Education",
    description:
      "Изпълнение на форхенд смеш от средната част на корта. Оценява се точност в 2 целеви зони отстрани или скорост.",
    equipment: "Радар или целеви зони на корта.",
    scoring: "Най-висока скорост (km/h) ИЛИ брой успешни попадения от 10.",
    focus: "Експлозивност, биомеханична верига.",
    scoreUnit: "т.",
    scoreType: "number",
  },
  {
    id: "u13_malaysia_agility",
    ageGroup: "U13",
    name: "Малайзийски тест (4 ъгъла)",
    source: "Badminton Asia",
    description:
      "Старт от центъра. Детето тича до 4-те ъгъла (по диагонали), за да вземе 4 пера и да ги върне в центъра едно по едно.",
    equipment: "4 пера, хронометър.",
    scoring: "Време за събиране на всички 4 пера.",
    focus: "Експлозивен старт, спиране и бърза смяна на посоката.",
    scoreUnit: "сек.",
    scoreType: "time",
  },
  {
    id: "u13_serve_receive",
    ageGroup: "U13",
    name: "Атака на къс сервис",
    source: "Badminton Europe",
    description:
      "Треньорът изпълнява къс сервис. Детето стартира от позиция за посрещане и изпълнява агресивен push или net kill.",
    equipment: "Треньор, пера.",
    scoring: "Успеваемост (от 10 опита). Перото трябва да мине бързо и ниско.",
    focus: "Реакция при сервис, експлозивна първа стъпка напред.",
    maxScore: 10,
    scoreUnit: "т.",
    scoreType: "number",
  },
  {
    id: "u13_complex_8_corners",
    ageGroup: "U13",
    name: "Тест 8 ъгъла (Complex Footwork)",
    source: "Badminton Asia",
    description:
      "Сложно движение, включващо 4-те ъгъла плюс 4-те междинни точки на корта.",
    equipment: "Корт, хронометър.",
    scoring: "Време за завършване на 1 пълен цикъл.",
    focus: "Координация при нестандартни ъгли на движение.",
    scoreUnit: "сек.",
    scoreType: "time",
  },
  {
    id: "u13_pace_control",
    ageGroup: "U13",
    name: "Ръководене на темпото (Pace Control)",
    source: "Badminton England",
    description:
      "Играчът трябва да смени темпото - 3 бързи плоски удара, последвани от 1 бавен дроп или висок клиър.",
    equipment: "Треньор за разиграване.",
    scoring: "Оценка на качеството на смяна на ритъма (1 до 10).",
    focus: "Тактическо мислене, контрол на разиграването.",
    maxScore: 10,
    scoreUnit: "т.",
    scoreType: "number",
  },
  {
    id: "u13_circuit_badminton",
    ageGroup: "U13",
    name: "Кръгова тренировка - Бадминтон специфика",
    source: "BWF Coach Education",
    description:
      "1 минута скокове на въже, 1 мин shadow footwork, 1 мин планк, 1 мин wall drive.",
    equipment: "Въже, корт, постелка, стена.",
    scoring: "Общ брой повторения във всички станции.",
    focus: "Обща физическа подготовка, силова издръжливост.",
    scoreUnit: "бр.",
    scoreType: "number",
  },

  // ================= U15 =================
  {
    id: "u15_jump_smash",
    ageGroup: "U15",
    name: "Смеш в движение (Jump Smash)",
    source: "BWF Level 2",
    description:
      "Детето се изнася назад от центъра, скача и забива от висока точка. Изпълняват се 10 опита.",
    equipment: "Треньор за подаване.",
    scoring: "Успеваемост: брой мощни удари в очертанията (от 10).",
    focus: "Тайминг на отскока, координация във въздуха, сила.",
    maxScore: 10,
    scoreUnit: "т.",
    scoreType: "number",
  },
  {
    id: "u15_smash_defense",
    ageGroup: "U15",
    name: "Защита от смеш",
    source: "Badminton Asia",
    description:
      "Треньорът забива към защитника. Защитникът трябва да блокира перото в целева зона близо до мрежата.",
    equipment: "Маркери в предна зона.",
    scoring: "10 опита. Брой успешни, контролирани блокове.",
    focus: "Рефлекси, нисък център на тежестта, мек хват.",
    maxScore: 10,
    scoreUnit: "т.",
    scoreType: "number",
  },
  {
    id: "u15_shuttle_run",
    ageGroup: "U15",
    name: 'Тест "Совалка" (Shuttle Run)',
    source: "Спортна физиология",
    description:
      "Тичане между двете странични линии (или 10 метра). Докосване на линията с ръка.",
    equipment: "Метър/Линии, хронометър.",
    scoring: "Брой отсечки за 1 минута.",
    focus: "Анаеробна издръжливост, бърза смяна на посоката.",
    scoreUnit: "бр.",
    scoreType: "number",
  },
  {
    id: "u15_cross_drop",
    ageGroup: "U15",
    name: "Крос-корт дроп шот",
    source: "BWF Level 2",
    description: "От заден десен ъгъл към преден ляв ъгъл (и обратно).",
    equipment: "Мишени в предните ъгли.",
    scoring: "10 опита по диагонал. Точкува се прецизността (1-3 т.).",
    focus: "Контрол на ъгъла на ракетата, трудна траектория.",
    maxScore: 30,
    scoreUnit: "т.",
    scoreType: "number",
  },
  {
    id: "u15_multi_feed_20",
    ageGroup: "U15",
    name: "Мулти-фийд Издръжливост (20 пера)",
    source: "BWF Coach Education",
    description:
      "Треньорът подава 20 пера в различни ъгли с високо темпо (1 перо на секунда). Играчът трябва да върне всяко.",
    equipment: "Кош с пера.",
    scoring: "Време до изпускане на темпото или брой успешно върнати пера.",
    focus: "Издръжливост под напрежение, възстановяване на позиция.",
    maxScore: 20,
    scoreUnit: "бр.",
    scoreType: "number",
  },
  {
    id: "u15_plank_core",
    ageGroup: "U15",
    name: "Издръжливост: Планк",
    source: "BWF Level 2 Physical",
    description:
      "Класически планк (на лакти). Оценява се базовата издръжливост на коремната и кръстната мускулатура.",
    equipment: "Постелка, хронометър.",
    scoring: "Време на задържане (в секунди или минути) с правилна форма.",
    focus: "Стабилизация на трупа, важна за предотвратяване на контузии.",
    scoreUnit: "сек.",
    scoreType: "time",
  },
  {
    id: "u15_attacking_drive_line",
    ageGroup: "U15",
    name: "Атакуващ Drive по правата",
    source: "Badminton Denmark",
    description:
      "Треньорът подава плоски пера. Играчът изпълнява силен, плосък удар (drive) по правата, търсейки задната линия.",
    equipment: "Треньор, пера, маркер на задната линия.",
    scoring: "От 10 опита, брой пера попаднали в последния 1 метър от корта.",
    focus: "Контрол на китката, скъсяване на маха, сила от предмишницата.",
    maxScore: 10,
    scoreUnit: "т.",
    scoreType: "number",
  },
  {
    id: "u15_left_right_smash",
    ageGroup: "U15",
    name: "Смеш от двете страни (Round-the-head Smash)",
    source: "BWF Level 2",
    description:
      "Треньорът подава в десния и левия (бекхенд) заден ъгъл алтернативно. Играчът използва round-the-head техника за левия ъгъл.",
    equipment: "Треньор, кош с пера.",
    scoring: "10 опита (по 5 в ъгъл). Брой точни и силни удари.",
    focus: "Round-the-head движение, мобилност на кръста.",
    maxScore: 10,
    scoreUnit: "т.",
    scoreType: "number",
  },
  {
    id: "u15_t_test_agility",
    ageGroup: "U15",
    name: "Agility T-Test",
    source: "Спортна физиология",
    description:
      "Спринт напред, настрани ляво, настрани дясно и назад, образувайки буквата Т с конуси.",
    equipment: "4 конуса, рулетка, хронометър.",
    scoring: "Време за преминаване.",
    focus: "Координация, децелерация, странично придвижване.",
    scoreUnit: "сек.",
    scoreType: "time",
  },
  {
    id: "u15_net_kill_spin",
    ageGroup: "U15",
    name: "Контрол над мрежата (Net Spin & Kill)",
    source: "Badminton Europe",
    description:
      "При високо подаване - kill, при ниско - spin. Треньорът редува височини на мрежата.",
    equipment: "Треньор на мрежата.",
    scoring: "Брой правилни решения и качествени удари от 20 опита.",
    focus: "Вземане на решения на мрежата, техника.",
    maxScore: 20,
    scoreUnit: "т.",
    scoreType: "number",
  },

  // ================= U17 =================
  {
    id: "u17_attacking_clear",
    ageGroup: "U17",
    name: "Атакуващ клиър (Attacking Clear)",
    source: "BWF Level 3",
    description:
      "Бърз, плосък клиър, който преминава точно над обсега на противника и пада бързо в задната зона.",
    equipment: "Маркери в задна зона.",
    scoring: "10 опита. Оценява се траекторията и скоростта.",
    focus: "Изненадваща атака, агресивно позициониране.",
    maxScore: 10,
    scoreUnit: "т.",
    scoreType: "number",
  },
  {
    id: "u17_defense_counter",
    ageGroup: "U17",
    name: "Защита с контраатака (Drive defense)",
    source: "Badminton Europe",
    description:
      "Защита на смеш чрез бърз drive удар в тялото/свободната зона на нападателя.",
    equipment: "Треньор забива.",
    scoring: "Брой успешни контраатаки от 10 смеша.",
    focus: "Преход от защита в атака, нападателен бекхенд.",
    maxScore: 10,
    scoreUnit: "т.",
    scoreType: "number",
  },
  {
    id: "u17_beep_test",
    ageGroup: "U17",
    name: "BWF Beep Test (Bleep Test)",
    source: "Стандартна физиология",
    description:
      "Многостепенен фитнес тест за аеробна издръжливост с прогресивно увеличаващо се темпо.",
    equipment: "Аудио запис за Beep Test, 20 метра разстояние.",
    scoring:
      "Ниво (Level) и совалка (Shuttle), до което е достигнал състезателят.",
    focus: "VO2 Max, максимална аеробна издръжливост.",
    scoreUnit: "Ниво",
    scoreType: "number",
  },
  {
    id: "u17_deceptive_drop",
    ageGroup: "U17",
    name: "Измамни удари (Deceptive drop)",
    source: "BWF Level 3",
    description:
      "Подготовка за силен клиър/смеш, последвана от забавяне (slice/reverse slice) за дроп шот.",
    equipment: "Мишени отпред.",
    scoring: "10 опита. Оценява се качеството на измамата и точността.",
    focus: "Забавяне на ракетата, движение на китката.",
    maxScore: 10,
    scoreUnit: "т.",
    scoreType: "number",
  },
  {
    id: "u17_shadow_1min",
    ageGroup: "U17",
    name: "Shadow Badminton (1 минута макс)",
    source: "Национални федерации",
    description:
      "Движение по корта без перо на 100% интензитет. Треньорът показва посоките (random feed).",
    equipment: "Треньор, хронометър.",
    scoring:
      "Оценява се поддържането на правилна техника в последните 15 секунди (Скала 1-10).",
    focus: "Лактатна толерантност, поддържане на техника при умора.",
    maxScore: 10,
    scoreUnit: "т.",
    scoreType: "number",
  },
  {
    id: "u17_illinois_agility",
    ageGroup: "U17",
    name: "Илинойс тест (Agility)",
    source: "Спортна физиология",
    description:
      "Специфичен тест за бързина със смяна на посоката около 4 конуса, подредени в линия на 10 метра разстояние.",
    equipment: "Конуси, метър, хронометър.",
    scoring: "Време за завършване на трасето.",
    focus: "Гъвкавост на глезените, ускорение, децелерация.",
    scoreUnit: "сек.",
    scoreType: "time",
  },
  {
    id: "u17_backhand_clear_deep",
    ageGroup: "U17",
    name: "Дълбок бекхенд клиър",
    source: "BWF Level 3",
    description:
      "От заден ляв ъгъл (за десничари), играчът трябва да изчисти перото с бекхенд до задната линия на противника.",
    equipment: "Маркери в задната зона.",
    scoring:
      "10 опита. 1 точка ако мине сервис линията, 2 точки ако стигне най-отзад.",
    focus: "Бекхенд биомеханика, супинация на ръката, тайминг.",
    maxScore: 20,
    scoreUnit: "т.",
    scoreType: "number",
  },
  {
    id: "u17_court_suicides",
    ageGroup: "U17",
    name: "Анаеробен тест на корта (Court Suicides)",
    source: "Национални федерации",
    description:
      "Совалково бягане от основна линия до всички напречни линии на корта и обратно, за минимално време.",
    equipment: "Корт, хронометър.",
    scoring: "Време за завършване на серията.",
    focus: "Максимална скорост и спиране.",
    scoreUnit: "сек.",
    scoreType: "time",
  },
  {
    id: "u17_defensive_lift_deep",
    ageGroup: "U17",
    name: "Дефанзивен лифт от трудна позиция",
    source: "BWF Level 3",
    description:
      "Треньорът забива силно в краката на играча. Играчът трябва да направи висок лифт до задната линия.",
    equipment: "Треньор забиващ, маркери.",
    scoring: "От 10 смеша, колко са лифтирани достатъчно дълбоко.",
    focus: "Оцеляване в защита, създаване на време.",
    maxScore: 10,
    scoreUnit: "т.",
    scoreType: "number",
  },
  {
    id: "u17_flick_serve",
    ageGroup: "U17",
    name: "Измамен сервис (Deceptive Flick Serve)",
    source: "Badminton Denmark",
    description:
      "Подготовка за къс сервис, но в последния момент движението се ускорява за дълъг (flick) сервис зад посрещащия.",
    equipment: "Маркери задна линия.",
    scoring: "Успешност на измамата и точността от 10 опита.",
    focus: "Контрол на палеца, липса на предварителни знаци (tell).",
    maxScore: 10,
    scoreUnit: "т.",
    scoreType: "number",
  },

  // ================= U19 =================
  {
    id: "u19_vertical_jump",
    ageGroup: "U19",
    name: "Тест за експлозивна сила (Vertical Jump)",
    source: "Спортна физиология",
    description: "Измерване на вертикалния отскок от място с изпъната ръка.",
    equipment: "Стена с метър или Vertec система.",
    scoring: "Височина на отскока в сантиметри.",
    focus: "Експлозивна сила на краката (за Jump Smash).",
    scoreUnit: "см.",
    scoreType: "number",
  },
  {
    id: "u19_fatigue_accuracy",
    ageGroup: "U19",
    name: "Точност под умора",
    source: "BWF Level 3",
    description:
      "След 30 секунди интензивен Shadow footwork, състезателят трябва да изпълни 5 прецизни удара по мишени.",
    equipment: "Мишени.",
    scoring: "Брой точни попадения (от 5).",
    focus: "Концентрация и моторно управление при висок пулс.",
    maxScore: 5,
    scoreUnit: "т.",
    scoreType: "number",
  },
  {
    id: "u19_smash_defense_series",
    ageGroup: "U19",
    name: "Смеш защита в серия (30 пера)",
    source: "Badminton Asia",
    description:
      "Двама подавачи забиват последователно 30 пера към състезателя без пауза.",
    equipment: "Двама забиващи, много пера.",
    scoring: "Брой върнати пера в очертанията.",
    focus: "Издръжливост в защита, бързина на реакциите.",
    maxScore: 30,
    scoreUnit: "бр.",
    scoreType: "number",
  },
  {
    id: "u19_drive_battle",
    ageGroup: "U19",
    name: "Двойки: Плоска игра (Drive battle)",
    source: "BWF Doubles Specific",
    description:
      "Двама състезатели играят бързи drives един срещу друг в предната 1/2 на корта.",
    equipment: "Корт, перо.",
    scoring:
      "Брой преминавания на перото над мрежата за 30 секунди без грешка.",
    focus: "Реакция, късо движение, хват.",
    scoreUnit: "бр.",
    scoreType: "number",
  },
  {
    id: "u19_match_serve",
    ageGroup: "U19",
    name: "Сервис под напрежение (20-20)",
    source: "Психологическа подготовка",
    description:
      "Изпълнение на сервис при симулирана ситуация на мач-пойнт (напр. със звуково смущение или физическо натоварване преди това).",
    equipment: "Корт.",
    scoring: "Процент успешност от 10 опита (целева зона).",
    focus: "Психологическа устойчивост, рутина.",
    maxScore: 10,
    scoreUnit: "т.",
    scoreType: "number",
  },
  {
    id: "u19_net_kill_reaction",
    ageGroup: "U19",
    name: "Рефлекс на мрежата (Net Kill)",
    source: "Badminton Asia",
    description:
      "Треньорът стои на мрежата и бързо подава/хвърля пера над филето. Играчът (също на мрежата) трябва мигновено да ги убие (kill).",
    equipment: "Треньор на кутия или отблизо, много пера.",
    scoring: "Брой успешни (не в мрежата или в аут) от 20 бързи подавания.",
    focus: "Супер бърз рефлекс, позиция на ракетата горе, къс хват.",
    maxScore: 20,
    scoreUnit: "бр.",
    scoreType: "number",
  },
  {
    id: "u19_broad_jump",
    ageGroup: "U19",
    name: "Скок на дължина от място",
    source: "Кондиционна подготовка",
    description:
      "Състезателят скача максимално напред от място с двата крака едновременно.",
    equipment: "Рулетка.",
    scoring: "Разстояние в сантиметри (най-добър от 3 опита).",
    focus:
      "Хоризонтална експлозивна мощ (важна за бързо излизане към мрежата).",
    scoreUnit: "см.",
    scoreType: "number",
  },
  {
    id: "u19_endurance_3vs1",
    ageGroup: "U19",
    name: "Комплексен тест за издръжливост (3 vs 1)",
    source: "Asian Elite Training",
    description:
      "Един играч играе срещу трима от другата страна, които подават бързо и разпределят. Рали до 21 точки.",
    equipment: "Трима спаринг партньори.",
    scoring: "Брой спечелени точки от единичния играч (от макс 21).",
    focus: "Пълно покриване на корта, екстремна издръжливост.",
    maxScore: 21,
    scoreUnit: "т.",
    scoreType: "number",
  },
  {
    id: "u19_smash_radar",
    ageGroup: "U19",
    name: "Сила на удара - Радар (Smash Radar)",
    source: "Спортна физиология",
    description:
      "Измерване на абсолютната максимална скорост на перото при Jump Smash.",
    equipment: "Скоростен радар, свежи пера.",
    scoring: "Максимална скорост в km/h от 5 опита.",
    focus: "Трансфер на сила от краката до китката.",
    scoreUnit: "km/h",
    scoreType: "number",
  },
  {
    id: "u19_rear_court_speed",
    ageGroup: "U19",
    name: "Бързина на придвижване назад",
    source: "Badminton England",
    description:
      "Старт от мрежата. Докосване на двата задни ъгъла последователно чрез специфично бадминтон придвижване.",
    equipment: "Хронометър.",
    scoring:
      "Време за 3 пълни повторения (мрежа -> заден ляв -> мрежа -> заден десен).",
    focus: "Оттласкване назад, китайска стъпка, ножичен отскок.",
    scoreUnit: "сек.",
    scoreType: "time",
  },

  // ================= Мъже и Жени =================
  {
    id: "adult_1rm_squat",
    ageGroup: "Мъже и Жени",
    name: "1RM Клек (Squat)",
    source: "Кондиционна подготовка",
    description:
      "Максимална тежест за едно повторение на клек с щанга (с правилна форма).",
    equipment: "Щанга, тежести.",
    scoring: "Вдигнати килограми.",
    focus: "Абсолютна сила на долната част на тялото.",
    scoreUnit: "кг.",
    scoreType: "number",
  },
  {
    id: "adult_smash_power_acc",
    ageGroup: "Мъже и Жени",
    name: "Смеш: Сила и Точност",
    source: "BWF High Performance",
    description:
      "Изпълнение на Jump Smash с максимална сила към мишена 30x30 см на страничната линия.",
    equipment: "Мишени 30x30 см.",
    scoring: "Брой попадения от 10 удара при поддържане на максимална сила.",
    focus:
      "Peak performance - пресечна точка между експлозивност и микро-точност.",
    maxScore: 10,
    scoreUnit: "т.",
    scoreType: "number",
  },
  {
    id: "adult_anaerobic_3min",
    ageGroup: "Мъже и Жени",
    name: "Анаеробна Издръжливост (3 мин)",
    source: "BWF High Performance",
    description:
      "Непрекъснато подаване на пера (multi-feed) във всички краища на корта за 3 минути (приблизителна дължина на много тежко разиграване).",
    equipment: "Треньор, 300+ пера.",
    scoring:
      "Измерване на спада в качеството на ударите през последната минута.",
    focus: "Екстремна лактатна толерантност.",
    scoreUnit: "% спад",
    scoreType: "number",
  },
  {
    id: "adult_tactical_recovery",
    ageGroup: "Мъже и Жени",
    name: "Тактическо възстановяване",
    source: "Badminton Europe",
    description:
      "Старт от позиция легнал по гръб. При сигнал играчът се изправя, отразява тежък удар в ъгъла и се връща в центъра.",
    equipment: "Хронометър, треньор.",
    scoring: "Време за реакция и връщане в позиция.",
    focus: "Възстановяване след загуба на баланс (dive).",
    scoreUnit: "сек.",
    scoreType: "time",
  },
  {
    id: "adult_decision_making",
    ageGroup: "Мъже и Жени",
    name: "Вземане на решения под стрес",
    source: "Когнитивна спортна психология",
    description:
      "Треньорът подава перо и в същия момент извиква цвят. Играчът трябва да изпълни специфичен удар, съответстващ на цвета.",
    equipment: "Кош с пера.",
    scoring: "Процент правилни решения (от 20).",
    focus: "Когнитивна обработка под физически стрес.",
    maxScore: 20,
    scoreUnit: "т.",
    scoreType: "number",
  },
  {
    id: "adult_yoyo_recovery",
    ageGroup: "Мъже и Жени",
    name: "Yo-Yo Intermittent Recovery Test",
    source: "BWF Elite Testing",
    description:
      "Подобен на Beep Test, но включва 10 секунди активна почивка (ходене) между всеки спринт от 2х20 метра. Много близък до спецификата на бадминтон разиграванията.",
    equipment: "Аудио запис за Yo-Yo test, маркери.",
    scoring: "Достигнато ниво и брой совалки.",
    focus:
      "Анаеробна издръжливост и способност за бързо възстановяване между разигравания.",
    scoreUnit: "Ниво",
    scoreType: "number",
  },
  {
    id: "adult_multishuttle_jump_smash",
    ageGroup: "Мъже и Жени",
    name: "20 поредни Jump Smash-a",
    source: "Asian Elite Training",
    description:
      "Треньорът подава 20 последователни високи пера. Играчът изпълнява Jump Smash на всяко едно, връщайки се леко след всеки отскок.",
    equipment: "Кош с пера.",
    scoring: "Време за завършване или брой грешки.",
    focus: "Лактатна издръжливост на краката и раменния пояс.",
    scoreUnit: "бр./сек.",
    scoreType: "number",
  },
  {
    id: "adult_vo2max_treadmill",
    ageGroup: "Мъже и Жени",
    name: "VO2 Max на тредмил",
    source: "Стандартна физиология",
    description:
      "Лабораторен тест на бягаща пътека с маска за анализ на газовете за прецизно определяне на максималното кислородно потребление.",
    equipment: "Тредмил, спирометър.",
    scoring: "VO2 Max (ml/kg/min).",
    focus: "Точна оценка на аеробния капацитет.",
    scoreUnit: "ml/kg/min",
    scoreType: "number",
  },
  {
    id: "adult_repeated_jump",
    ageGroup: "Мъже и Жени",
    name: "Повтарящ се експлозивен отскок",
    source: "Спортна физиология",
    description:
      "15 последователни максимални вертикални отскока без пауза върху контактна платформа.",
    equipment: "Контактна платформа (Jump mat).",
    scoring:
      "Индекс на умората (Fatigue Index) - разлика между първия и последния скок.",
    focus: "Поддържане на експлозивност, реактивна сила.",
    scoreUnit: "%",
    scoreType: "number",
  },
  {
    id: "adult_high_hr_accuracy",
    ageGroup: "Мъже и Жени",
    name: "Точност при пулс 180+ (High HR Accuracy)",
    source: "BWF High Performance",
    description:
      "Играчът е докаран до пулс 180+ чрез 45 сек. бърз мулти-фийд, след което веднага трябва да изпълни 3 фини мрежови удара (tumble spin).",
    equipment: "Пулсомер, треньор.",
    scoring: "Успешност на фините удари (от 1 до 10 качество).",
    focus:
      "Спортно майсторство, контрол на фината моторика при изключителен стрес.",
    maxScore: 10,
    scoreUnit: "т.",
    scoreType: "number",
  },
];
