import { Exercise } from "@/types/planner.types";

export const ALL_EXERCISES: Omit<
  Exercise,
  "id" | "siteId" | "createdAt" | "updatedAt"
>[] = [
  {
    name: "Топка на тигана (BWF Racket Control)",
    category: "technique",
    phase: "warmup",
    source: "BWF Shuttle Time - Lesson 3",
    description:
      "Дръжте ракетата като тиган (хват за форхенд на мрежата) и тупкайте перото леко нагоре към тавана. Нека видим кой може да направи 10 удара без да изпусне перото!",
    coachingPoints: [
      "BWF Насока: Следи за 'Panhandle Grip' (хват тип тиган). Палецът не трябва да е плосък на дръжката.",
      "Грешка: Децата стягат китката. Корекция: Кажи им да държат ракетата леко, като крехко яйце.",
      "Надграждане: Ако са добри, накарай ги да тупкат перото, докато ходят.",
    ],
    durationMinutes: 5,
    location: ["court"],
    ageGroups: ["U9", "U11"],
    equipment: ["Ракети", "Пера"],
    intensity: 2,
    complexityLevel: 1,
    prerequisites: ["Основен хват"],
  },
  {
    name: "Обръщане на палачинката (BWF Grip Change)",
    category: "technique",
    phase: "warmup",
    source: "BWF Shuttle Time - Lesson 4",
    description:
      "Тупкаме перото веднъж с едната страна на ракетата (черната), а следващият път я завъртаме бързо в ръката и тупкаме с другата страна (червената). Обръщайте 'палачинката' във въздуха!",
    coachingPoints: [
      "BWF Насока: Учи децата да въртят ракетата в пръстите, а не да извиват цялата китка или лакът.",
      "Грешка: Въртят цялата ръка. Корекция: Покажи им как ракетата се върти само с палеца и показалеца.",
    ],
    durationMinutes: 5,
    location: ["court"],
    ageGroups: ["U9", "U11", "U13"],
    equipment: ["Ракети", "Пера"],
    intensity: 2,
    complexityLevel: 2,
    prerequisites: ["Основен хват"],
  },
  {
    name: "Хвани с ръка, хвърли с ръка (BWF Throwing Base)",
    category: "technique",
    phase: "warmup",
    source: "BWF Shuttle Time - Lesson 5",
    description:
      "Без ракети! Заставаме един срещу друг. Аз хвърлям перото отдолу-нагоре към теб, а ти трябва да го хванеш. После ти ми го хвърляш обратно.",
    coachingPoints: [
      "BWF Насока: Хвърлянето и хващането са основата за тайминга на всички удари.",
      "Грешка: Хвърлят със сгънат лакът. Корекция: Ръката трябва да е изпъната като махало при долно хвърляне.",
    ],
    durationMinutes: 5,
    location: ["court"],
    ageGroups: ["U9", "U11"],
    equipment: ["Пера"],
    intensity: 2,
    complexityLevel: 1,
    prerequisites: ["Основен хват"],
  },
  {
    name: "Рисуване на осмици (BWF Figure of 8 Grip)",
    category: "technique",
    phase: "warmup",
    source: "BWF Shuttle Time - Grip",
    description:
      "Хващаме ракетата нормално. Без перо! Използваме главата на ракетата, за да 'нарисуваме' голяма осмица във въздуха. Трябва да усетите как ракетата се върти в пръстите ви.",
    coachingPoints: [
      "Учи децата на фин контрол с пръстите (Finger Power).",
      "Рамото и лакътят трябва да са относително неподвижни, работата се върши от китката и пръстите.",
    ],
    durationMinutes: 5,
    location: ["court"],
    ageGroups: ["U9", "U11", "U13"],
    equipment: ["Ракети"],
    intensity: 1,
    complexityLevel: 2,
    prerequisites: ["Основен хват"],
  },
  {
    name: "Удряне на перо в стената (BWF Wall Rally)",
    category: "technique",
    phase: "warmup",
    source: "BWF Level 1 - Wall Practice",
    description:
      "Заставаме на 1 метър от стената. Тупкаме перото в стената с бекхенд хват. Колко удара можеш да направиш, преди да падне?",
    coachingPoints: [
      "Идеално за развиване на бърз бекхенд драйв и защитни рефлекси.",
      "Следи палецът да е изпънат на плоската страна на дръжката.",
    ],
    durationMinutes: 10,
    location: ["court"],
    ageGroups: ["U11", "U13", "U15"],
    equipment: ["Ракети", "Пера"],
    intensity: 3,
    complexityLevel: 3,
    prerequisites: ["Основен хват"],
  },
  {
    name: "Ножичен отскок (BWF Scissor Jump - Сянка)",
    category: "technique",
    phase: "main-tech",
    source: "BWF Coach Education Level 1 - Module 4",
    description:
      "Заставаме зад линията за сервиз. Десният крак е назад. Скачаме нагоре, въртим тялото във въздуха и се приземяваме с десния крак напред (като ножица). Удряме невидимо перо докато сме горе!",
    coachingPoints: [
      "BWF Насока: Завъртането на таза е източникът на силата (Body rotation).",
      "Грешка: Приземяват се на два крака едновременно. Корекция: Първо пада кракът от страната на ракетата (ракетен крак), после другият.",
    ],
    durationMinutes: 10,
    location: ["court"],
    ageGroups: ["U11", "U13", "U15", "U17"],
    equipment: ["Ракети"],
    intensity: 4,
    complexityLevel: 3,
    prerequisites: ["Основен хват"],
  },
  {
    name: "Сплит стъпка (BWF Split Drop)",
    category: "technique",
    phase: "warmup",
    source: "BWF Coach Education Level 1 - Movement",
    description:
      "Всички подскачат леко на място. Когато плесна с ръце (чуете звука на удара), краката ви се разтварят малко по-широко и пружинират надолу, готови за старт!",
    coachingPoints: [
      "BWF Насока: 'Split step' се прави точно когато противникът удря перото.",
      "Грешка: Скачат високо нагоре. Корекция: Сплит стъпката е пропадане надолу за зареждане на краката, не скок във въздуха.",
    ],
    durationMinutes: 5,
    location: ["court"],
    ageGroups: ["U9", "U11", "U13", "U15", "U17", "Мъже и Жени"],
    equipment: ["Ракети", "Пера"],
    intensity: 3,
    complexityLevel: 2,
    prerequisites: ["Основен хват"],
  },
  {
    name: "Напад към мрежата (BWF Lunge Technique)",
    category: "technique",
    phase: "main-tech",
    source: "BWF Coach Education Level 1 - Module 4",
    description:
      "Тръгваме от центъра, правим две бързи крачки (Chasse) и широка крачка към мрежата (Напад). Петата на предния крак трябва да удари първа пода. Издърпваме се назад!",
    coachingPoints: [
      "BWF Насока: 'Heel-toe landing' (Първо петата, после пръстите) за предния крак.",
      "Грешка: Коляното минава пред пръстите на крака. Корекция: Спри ги, покажи им как това вреди на ставата.",
      "Грешка 2: Задният крак се вдига от земята. Корекция: Задният крак се влачи вътрешната част на ходилото за баланс.",
    ],
    durationMinutes: 10,
    location: ["court"],
    ageGroups: ["U11", "U13", "U15", "U17", "Мъже и Жени"],
    equipment: ["Ракети"],
    intensity: 4,
    complexityLevel: 3,
    prerequisites: ["Основен хват"],
  },
  {
    name: "V-Front Footwork (BWF 6-Point Movement)",
    category: "technique",
    phase: "main-tech",
    source: "BWF Level 1 - Shadow Badminton",
    description:
      "Треньорът сочи напред-ляво или напред-дясно. Вие правите Сплит стъпка, бързи крачки, напад към посочения ъгъл, въображаем удар и бързо връщане в центъра!",
    coachingPoints: [
      "BWF Насока: Завръщането в базата става с отблъскване от предния крак и кръстосана или шасе стъпка назад.",
      "Следи дали ракетата е вдигната, докато тичат към мрежата.",
    ],
    durationMinutes: 15,
    location: ["court"],
    ageGroups: ["U11", "U13", "U15", "U17"],
    equipment: ["Ракети"],
    intensity: 5,
    complexityLevel: 3,
    prerequisites: ["Основен хват"],
  },
  {
    name: "V-Back Footwork (BWF 6-Point Back)",
    category: "technique",
    phase: "main-tech",
    source: "BWF Level 1 - Shadow Badminton",
    description:
      "От центъра се изтегляме бързо назад към левия или десния ъгъл с Шасе стъпки. Правим скок с ножица (Scissor Jump), въображаем смач и бързо се връщаме в центъра.",
    coachingPoints: [
      "Движението назад винаги започва с леко изтласкване от предния крак.",
      "Тялото трябва да е странично (страничен профил) докато бягат назад.",
    ],
    durationMinutes: 10,
    location: ["court"],
    ageGroups: ["U13", "U15", "U17"],
    equipment: ["Ракети"],
    intensity: 5,
    complexityLevel: 4,
    prerequisites: ["Основен хват"],
  },
  {
    name: "Защитно придвижване (BEC Side-to-side Defense)",
    category: "technique",
    phase: "main-tech",
    source: "Badminton Europe - Defense",
    description:
      "Краката са широко разтворени. Треньорът сочи вляво или вдясно. Правите един голям разкрач (страничен напад), докосвате пода с ракетата (като връщане на смач) и бързо се връщате.",
    coachingPoints: [
      "Центърът на тежестта е изключително ниско (почти в клек).",
      "Използвайте бекхенд хват и за двете страни за по-бърза реакция.",
    ],
    durationMinutes: 10,
    location: ["court"],
    ageGroups: ["U13", "U15", "U17", "Мъже и Жени"],
    equipment: ["Ракети"],
    intensity: 4,
    complexityLevel: 3,
    prerequisites: ["Основен хват"],
  },
  {
    name: "Хвърляне на въображаемо перо (BWF Overhead Action)",
    category: "technique",
    phase: "main-tech",
    source: "BWF Coach Education Level 1 - Module 5",
    description:
      "Хващаме едно перо. Заставаме странично на мрежата, вдигаме ръцете горе (като буквата Х) и хвърляме перото максимално силно към отсрещното поле!",
    coachingPoints: [
      "BWF Насока: Перфектна прогресия за заучаване на Смач/Клиър без ракета.",
      "Грешка: Хвърлят перото с твърда китка. Корекция: Изисквай камшично движение и пронация на предмишницата.",
      "Наблюдавай смяната на краката при хвърлянето.",
    ],
    durationMinutes: 10,
    location: ["court", "stadium"],
    ageGroups: ["U9", "U11", "U13"],
    equipment: ["Пера"],
    intensity: 3,
    complexityLevel: 2,
    prerequisites: ["Основен хват"],
  },
  {
    name: "Обикновено изчистване (BWF Overhead Clear)",
    category: "technique",
    phase: "main-tech",
    source: "BWF Level 1 - Strokes",
    description:
      "Играем само дълги и високи топки от задна линия до задна линия. Целта е перото да падне отвесно в задния коридор на противника.",
    coachingPoints: [
      "BWF Насока: Точката на контакт трябва да е високо горе и леко пред тялото.",
      "Грешка: Удрят перото зад главата си (огъват гърба). Корекция: Трябва да се движат по-бързо назад, за да е перото пред тях.",
    ],
    durationMinutes: 15,
    location: ["court"],
    ageGroups: ["U11", "U13", "U15", "U17", "Мъже и Жени"],
    equipment: ["Ракети", "Пера"],
    intensity: 3,
    complexityLevel: 3,
    prerequisites: ["Основен хват"],
  },
  {
    name: "Бърз Смач (BWF Smash Action)",
    category: "technique",
    phase: "main-tech",
    source: "BWF Level 1 - Overhead",
    description:
      "Подавам лесни високи пера в центъра. Искам да ги забивате максимално силно и стръмно право надолу!",
    coachingPoints: [
      "Смачът изисква ускорение. 'Стисни ракетата силно в момента на удара' (Tighten grip on impact).",
      "След удара ракетата трябва да премине покрай противоположния крак (Follow through).",
    ],
    durationMinutes: 10,
    location: ["court"],
    ageGroups: ["U13", "U15", "U17", "Мъже и Жени"],
    equipment: ["Ракети", "Пера"],
    intensity: 4,
    complexityLevel: 3,
    prerequisites: ["Основен хват"],
  },
  {
    name: "Отсечено Скъсяване (BWF Slice Drop)",
    category: "technique",
    phase: "main-tech",
    source: "BEC Coach Education",
    description:
      "Замахвате мощно все едно ще правите смач, но в последния момент 'отрязвате' перото с леко завъртане на ракетата, така че да падне бавно близо до мрежата.",
    coachingPoints: [
      "Скоростта на ръката трябва да е същата като при смач! Иначе противникът ще познае какво правите.",
      "Удряме перото под ъгъл (Slice) за да убием скоростта му.",
    ],
    durationMinutes: 15,
    location: ["court"],
    ageGroups: ["U15", "U17", "Мъже и Жени"],
    equipment: ["Ракети", "Пера"],
    intensity: 3,
    complexityLevel: 4,
    prerequisites: ["Основен хват"],
  },
  {
    name: "Lift от мрежата (BWF Underarm Clear)",
    category: "technique",
    phase: "main-tech",
    source: "BWF Level 1 - Underarm Strokes",
    description:
      "Треньорът пуска пера съвсем близо до мрежата. Вие правите голям напад и изстрелвате перото високо към тавана чак до крайната линия на отсрещното поле!",
    coachingPoints: [
      "BWF Насока: За силен Лифт движението идва от предмишницата (Supination/Pronation) и китката, не от голям замах от рамото.",
      "Грешка: Голям тенис-замах. Корекция: Стегни движението, удари 'отдолу-нагоре'.",
    ],
    durationMinutes: 15,
    location: ["court"],
    ageGroups: ["U11", "U13", "U15"],
    equipment: ["Ракети", "Пера"],
    intensity: 4,
    complexityLevel: 3,
    prerequisites: ["Основен хват"],
  },
  {
    name: "Къса топка (BWF Net Drop)",
    category: "technique",
    phase: "main-tech",
    source: "BWF Level 1 - Net Play",
    description:
      "Искам само да подложите ракетата (без замах!) и да накарате перото да се претърколи през бялата лента на мрежата.",
    coachingPoints: [
      "BWF Насока: Ракетата е вдигната преди напада да приключи.",
      "Грешка: Замахват, за да ударят къса топка. Корекция: Думата не е 'удар', а 'насочване' с пръстите.",
    ],
    durationMinutes: 15,
    location: ["court"],
    ageGroups: ["U11", "U13", "U15", "U17", "Мъже и Жени"],
    equipment: ["Ракети", "Пера"],
    intensity: 2,
    complexityLevel: 4,
    prerequisites: ["Основен хват"],
  },
  {
    name: "Добиване на мрежата (BWF Net Kill)",
    category: "technique",
    phase: "main-tech",
    source: "BWF Coach Level 2",
    description:
      "Ако перото е дори малко над мрежата, скачаме бързо и го 'добиваме' рязко с движение само от китката и пръстите. Никакъв замах назад, за да не ударим мрежата!",
    coachingPoints: [
      "Хватката е лека, стяга се рязко при контакта.",
      "Грешка: Използват цялата ръка и удрят мрежата. Корекция: Дръж лакътя стабилен, използвай само четката (squeeze the grip).",
    ],
    durationMinutes: 10,
    location: ["court"],
    ageGroups: ["U15", "U17", "Мъже и Жени"],
    equipment: ["Ракети", "Пера"],
    intensity: 4,
    complexityLevel: 3,
    prerequisites: ["Основен хват"],
  },
  {
    name: "Атакуващ Драйв (BWF Flat Drive)",
    category: "technique",
    phase: "main-tech",
    source: "BEC Coach Education",
    description:
      "Двама играчи застават малко пред средата на корта. Разменяте си много бързи, плоски удари на нивото на очите. Перото не трябва да се вдига високо!",
    coachingPoints: [
      "Ракетата трябва винаги да е пред тялото.",
      "Клякаме леко, за да сме на нивото на перото.",
    ],
    durationMinutes: 10,
    location: ["court"],
    ageGroups: ["U13", "U15", "U17", "Мъже и Жени"],
    equipment: ["Ракети", "Пера"],
    intensity: 4,
    complexityLevel: 3,
    prerequisites: ["Основен хват"],
  },
  {
    name: "Сервиз 'Бекхенд' къс (BWF Backhand Short Serve)",
    category: "technique",
    phase: "warmup",
    source: "BWF Level 1 - Serves",
    description:
      "Хващаме перото за връхчето на едно перце. Ракетата е пред тялото (бекхенд хват). Леко бутаме перото с палеца, за да мине точно на 2 сантиметра над мрежата.",
    coachingPoints: [
      "Следи перото да се удря под нивото на долното ребро (правило за сервиз).",
      "Краката са неподвижни, тежестта е леко на предния крак.",
    ],
    durationMinutes: 10,
    location: ["court"],
    ageGroups: ["U11", "U13", "U15", "U17", "Мъже и Жени"],
    equipment: ["Ракети", "Пера"],
    intensity: 1,
    complexityLevel: 3,
    prerequisites: ["Основен хват"],
  },
  {
    name: "Атакуващо мулти (BEC Multishuttle Smash & Net)",
    category: "technique",
    phase: "main-tech",
    source: "Badminton Europe Coach Manual",
    description:
      "Подавам 15 пера много бързо! Първото е високо за Смач, второто е късо за мрежа. Удряте, отскачате, удряте! Дайте 100% от себе си!",
    coachingPoints: [
      "BEC Насока: Подаващият диктува темпото. Ако детето е добро, подавай перото ПРЕДИ то да се е върнало в база.",
      "Цел: Развитие на анаеробна издръжливост и плавно преминаване от удар в удар.",
    ],
    durationMinutes: 15,
    location: ["court"],
    ageGroups: ["U13", "U15", "U17", "Мъже и Жени"],
    equipment: ["Пера"],
    intensity: 5,
    complexityLevel: 4,
    defaultSets: 4,
    defaultWorkSec: 30,
    defaultRestSec: 60,
    prerequisites: ["Основен хват"],
  },
  {
    name: "Защитно мулти (BEC Defense Drill)",
    category: "technique",
    phase: "main-tech",
    source: "Badminton Europe Coach Manual",
    description:
      "Вие сте клекнали леко в защита. Аз забивам пера право във вас (от коша) едно след друго. Искам да ги връщате дълбоко в моето поле!",
    coachingPoints: [
      "BEC Насока: Хват за бекхенд (Backhand Grip) при защита, ракетата е пред тялото.",
      "Грешка: Разпъват ръката встрани за форхенд. Корекция: 80% от защитата се играе с бекхенд около тялото.",
    ],
    durationMinutes: 15,
    location: ["court"],
    ageGroups: ["U15", "U17", "Мъже и Жени"],
    equipment: ["Пера"],
    intensity: 4,
    complexityLevel: 4,
    prerequisites: ["Основен хват"],
  },
  {
    name: "Мулти за издръжливост - 20 пера (BEC Clear Endurance)",
    category: "technique",
    phase: "main-tech",
    source: "BEC High Performance",
    description:
      "Треньорът подава 20 пера бързо към задните два ъгъла. Играчът прави Шасе стъпки, изчиства силно и веднага търчи към другия ъгъл. Без спиране!",
    coachingPoints: [
      "Упражнение до отказ. Следи за правилна техника на краката дори когато играчът е уморен.",
      "Сърдечният ритъм се вдига драстично. Задължителна почивка от 60+ секунди между сериите.",
    ],
    durationMinutes: 15,
    location: ["court"],
    ageGroups: ["U15", "U17", "Мъже и Жени"],
    equipment: ["Пера"],
    intensity: 5,
    complexityLevel: 4,
    defaultSets: 5,
    defaultWorkSec: 40,
    defaultRestSec: 90,
    prerequisites: ["Основен хват"],
  },
  {
    name: "Случайно подаване (Random Feed Agility)",
    category: "technique",
    phase: "main-tech",
    source: "Asian Badminton Training",
    description:
      "Подавам 15 пера напълно произволно - мрежа, отзад, смач, драйв. Играчът не знае къде ще отиде следващото перо и разчита само на рефлекс и Split Step.",
    coachingPoints: [
      "Учи играча на истинско взимане на решения (Decision making).",
      "Split Step е абсолютно критичен тук, иначе играчът закъснява.",
    ],
    durationMinutes: 15,
    location: ["court"],
    ageGroups: ["U15", "U17", "Мъже и Жени"],
    equipment: ["Пера"],
    intensity: 5,
    complexityLevel: 5,
    prerequisites: ["Основен хват"],
  },
  {
    name: "Игра на дължина (BWF Front/Back Court Game)",
    category: "tactics",
    phase: "main-tact",
    source: "BWF Level 1 - Tactics",
    description:
      "Играем мач, но правилото е: един удар на мрежата, следващият удар задължително на задна линия. Принудете противника да бяга от край до край!",
    coachingPoints: [
      "BWF Насока: Учи децата на базовата концепция 'преместване на противника'.",
      "Следи дали успяват да изчистят перото достатъчно назад.",
    ],
    durationMinutes: 20,
    location: ["court"],
    ageGroups: ["U13", "U15", "U17"],
    equipment: ["Ракети", "Пера"],
    intensity: 4,
    complexityLevel: 3,
    prerequisites: [],
  },
  {
    name: "Само Скъсявания (BEC Tactical Constraint)",
    category: "tactics",
    phase: "main-tact",
    source: "Badminton Europe Summer School",
    description:
      "Искам да играем мач, но СМАЧЪТ е абсолютно ЗАБРАНЕН! Завършването на атаката става само със Скъсяване (бърза къса топка) и игра на мрежата.",
    coachingPoints: [
      "Учи играчите да използват ъгли и скорост вместо само груба сила.",
      "Гледай дали подготвят удара като за смач, за да излъжат противника (Deception).",
    ],
    durationMinutes: 20,
    location: ["court"],
    ageGroups: ["U13", "U15", "U17", "Мъже и Жени"],
    equipment: ["Ракети", "Пера"],
    intensity: 3,
    complexityLevel: 4,
    prerequisites: [],
  },
  {
    name: "Атака и Защита (BWF Attack vs Defense Game)",
    category: "tactics",
    phase: "main-tact",
    source: "BWF Advanced Tactics",
    description:
      "Единият играч може само да атакува (Смач, Скъсяване), а другият може само да се защитава (Лоб, Високо изчистване). Играят до 11 точки и си сменят ролите.",
    coachingPoints: [
      "Много добро упражнение за развиване на специализирани навици (как да пробиеш защита или как да не се предаваш).",
      "Следи защитникът да стои по-дълбоко в корта.",
    ],
    durationMinutes: 20,
    location: ["court"],
    ageGroups: ["U15", "U17", "Мъже и Жени"],
    equipment: ["Ракети", "Пера"],
    intensity: 5,
    complexityLevel: 4,
    prerequisites: [],
  },
  {
    name: "Двойки - Атакуваща формация (BWF Doubles Attack)",
    category: "tactics",
    phase: "main-tact",
    source: "BWF Doubles Specific",
    description:
      "Тренираме формация 'Преден и Заден играч'. Треньорът вдига високи пера. Задният прави смач, предният пази мрежата с вдигната ракета и довършва късите отговори.",
    coachingPoints: [
      "Предният играч не се обръща назад! Той гледа само напред и пази мрежата.",
      "Задният играч покрива цялата задна линия.",
    ],
    durationMinutes: 15,
    location: ["court"],
    ageGroups: ["U15", "U17", "Мъже и Жени"],
    equipment: ["Ракети", "Пера"],
    intensity: 4,
    complexityLevel: 5,
    prerequisites: [],
  },
  {
    name: "Шасе Спринт (BWF Physical Conditioning)",
    category: "physical",
    phase: "main-tech",
    source: "BWF Level 1 - Physical",
    description:
      "Заставаме на страничната линия. Правим Шасе (chasse) стъпки странично до другата линия, докосваме я и се връщаме обратно колкото се може по-бързо!",
    coachingPoints: [
      "BWF Насока: Краката не трябва да се кръстосват при Шасе. Те не трябва да се удрят един в друг.",
      "Следи центърът на тежестта да е ниско (да не подскачат нагоре).",
    ],
    durationMinutes: 10,
    location: ["court", "stadium"],
    ageGroups: ["U11", "U13", "U15", "U17", "Мъже и Жени"],
    equipment: ["Ракети", "Пера"],
    intensity: 5,
    complexityLevel: 2,
    defaultSets: 5,
    defaultWorkSec: 30,
    defaultRestSec: 45,
    prerequisites: [],
  },
  {
    name: "Жабешки скокове - Дължина (BEC Core Leg Strength)",
    category: "physical",
    phase: "main-tech",
    source: "BEC Conditioning Profile",
    description:
      "Клякаме дълбоко, ръцете докосват земята, и скачаме силно напред, колкото можем по-далеч. 10 скока по дължината на залата.",
    coachingPoints: [
      "Изгражда експлозивна сила, необходима за напади (lunges).",
      "Грешка: Приземяване на прави крака. Корекция: Амортизирай приземяването, като клекнеш отново.",
    ],
    durationMinutes: 10,
    location: ["court", "stadium"],
    ageGroups: ["U13", "U15", "U17", "Мъже и Жени"],
    equipment: ["Ракети", "Пера"],
    intensity: 4,
    complexityLevel: 2,
    prerequisites: [],
  },
  {
    name: "Лицеви опори (BWF Core Stability)",
    category: "physical",
    phase: "main-tech",
    source: "BWF Level 1 - Physical",
    description:
      "Правим лицеви опори (за най-малките може на колене). Гърбът е прав като дъска, слизаме бавно надолу и се избутваме силно нагоре.",
    coachingPoints: [
      "В бадминтона ръцете и ядрото трябва да са силни за ротацията при удара.",
      "Грешка: Дупето хлътва надолу.",
    ],
    durationMinutes: 10,
    location: ["court"],
    ageGroups: ["U13", "U15", "U17", "Мъже и Жени"],
    equipment: ["Ракети", "Пера"],
    intensity: 4,
    complexityLevel: 2,
    prerequisites: [],
  },
  {
    name: "Планк за ядро (BWF Core Plank)",
    category: "physical",
    phase: "main-tech",
    source: "BWF Conditioning",
    description:
      "Заставаме на лакти и пръсти на краката. Гърбът е идеално прав. Държим така 45-60 секунди без да мърдаме.",
    coachingPoints: [
      "Ядрото (Core) е центърът на баланса в бадминтона. Без здрав корем, ударите във въздуха са невъзможни.",
    ],
    durationMinutes: 5,
    location: ["court", "stadium"],
    ageGroups: ["U13", "U15", "U17", "Мъже и Жени"],
    equipment: ["Ракети", "Пера"],
    intensity: 4,
    complexityLevel: 1,
    defaultSets: 3,
    defaultWorkSec: 45,
    defaultRestSec: 30,
    prerequisites: [],
  },
  {
    name: "Странични подскоци през линия (BEC Side Jumps)",
    category: "physical",
    phase: "main-tech",
    source: "BEC Conditioning",
    description:
      "Заставаме до една линия на корта. Събрани крака. Скачаме вляво и вдясно през линията максимално бързо за 30 секунди.",
    coachingPoints: [
      "Тренира бързите мускулни влакна и силата на прасците.",
      "Петите не докосват земята, скача се само на възглавничките (предните части на стъпалото).",
    ],
    durationMinutes: 5,
    location: ["court", "stadium"],
    ageGroups: ["U13", "U15", "U17", "Мъже и Жени"],
    equipment: ["Ракети", "Пера"],
    intensity: 5,
    complexityLevel: 2,
    defaultSets: 3,
    defaultWorkSec: 30,
    defaultRestSec: 45,
    prerequisites: [],
  },
  {
    name: "Спринт 5 метра (BWF Acceleration)",
    category: "physical",
    phase: "main-tech",
    source: "BWF Speed Drills",
    description:
      "Спринт от централната линия до мрежата. Докосване и бавно връщане назад. Повтаряме 10 пъти.",
    coachingPoints: [
      "В бадминтона никой не тича 100 метра. Най-важното е ускорението на разстояние от 2 до 5 метра.",
    ],
    durationMinutes: 10,
    location: ["court", "stadium"],
    ageGroups: ["U11", "U13", "U15", "U17", "Мъже и Жени"],
    equipment: ["Ракети", "Пера"],
    intensity: 5,
    complexityLevel: 1,
    prerequisites: [],
  },
  {
    name: "Бомба в полето (BWF Throwing Game)",
    category: "games",
    phase: "warmup",
    source: "BWF Shuttle Time - Fun Games",
    description:
      "Разделяме залата на две. Давам ви 30 пера ('бомби'). Трябва да хвърляте перата с ръка над мрежата в полето на противника. Като кажа 'СТОП', печели отборът с по-малко пера при тях!",
    coachingPoints: [
      "BWF Насока: Изисквай да хвърлят отгоре (Overhead throw), за да тренират замаха за Смач.",
      "Супер забавно упражнение, децата се движат нон-стоп.",
    ],
    durationMinutes: 5,
    location: ["court"],
    ageGroups: ["U9", "U11", "U13"],
    equipment: ["Пера"],
    intensity: 4,
    complexityLevel: 1,
    prerequisites: [],
  },
  {
    name: "Удари кутията (BWF Target Game)",
    category: "games",
    phase: "main-tech",
    source: "BWF Shuttle Time - Net/Serve Games",
    description:
      "Строим кулички от туби с пера. Тренираме къс сервиз. Ако уцелиш кулата и я бутнеш - получаваш 10 точки за отбора си!",
    coachingPoints: [
      "BWF Насока: Обучение чрез мишена ('Target practice'). Държи вниманието на децата много повече от празната мрежа.",
      "Проверявай дали държат правилно ракетата и перото при сервиз.",
    ],
    durationMinutes: 10,
    location: ["court"],
    ageGroups: ["U9", "U11", "U13", "U15"],
    equipment: ["Ракети", "Пера"],
    intensity: 2,
    complexityLevel: 2,
    prerequisites: [],
  },
  {
    name: "Цар на корта (BEC Classic)",
    category: "games",
    phase: "main-tact",
    source: "Badminton Europe - Games",
    description:
      "Едното поле е 'Царското'. Който спечели точка, отива в него. Ако царят загуби, се връща на опашката. Целта е да останеш цар най-дълго!",
    coachingPoints: [
      "Развива състезателен манталитет под напрежение.",
      "Ако децата са много, играйте точки само до 2 или до първа грешка, за да се въртят бързо.",
    ],
    durationMinutes: 15,
    location: ["court"],
    ageGroups: ["U11", "U13", "U15", "U17", "Мъже и Жени"],
    equipment: ["Ракети", "Пера"],
    intensity: 4,
    complexityLevel: 3,
    prerequisites: [],
  },
  {
    name: "Хвани опашката на дракона (BWF Catch the Tail)",
    category: "games",
    phase: "warmup",
    source: "BWF Shuttle Time - Agility",
    description:
      "Всяко дете пъха едно перо (или лента) в колана на шортите си отзад (като опашка). Целта е да откраднеш чуждите опашки, докато пазиш своята. Който остане с най-много, печели!",
    coachingPoints: [
      "Тренира изключително добре ловкост (Agility) и бърза смяна на посоката.",
    ],
    durationMinutes: 5,
    location: ["court", "stadium"],
    ageGroups: ["U9", "U11", "U13"],
    equipment: ["Пера"],
    intensity: 5,
    complexityLevel: 1,
    prerequisites: [],
  },
  {
    name: "Събирачи на съкровища (Treasure Collectors)",
    category: "games",
    phase: "warmup",
    source: "BWF Shuttle Time - Speed",
    description:
      "Разпръсваме 50 пера из корта (съкровищата). Отборите са в ъглите с по една празна туба. Когато кажа 'СТАРТ', децата тичат, взимат ЕДНО перо и го носят в тубата. Печели отборът с най-много пера.",
    coachingPoints: [
      "Учи децата на бързи спринтове, навеждане (напад) и връщане към базата.",
    ],
    durationMinutes: 5,
    location: ["court", "stadium"],
    ageGroups: ["U9", "U11", "U13"],
    equipment: ["Пера"],
    intensity: 4,
    complexityLevel: 1,
    prerequisites: [],
  },
  {
    name: "Групово разтягане (BEC Cool-Down Protocol)",
    category: "cooldown",
    phase: "cooldown",
    source: "Badminton Europe Coach Manual",
    description:
      "Сядаме в кръг на пода. Хващаме си глезените и разтягаме вътрешната част на бедрата (Пеперуда). Дишаме дълбоко. Треньорът дава оценка на тренировката.",
    coachingPoints: [
      "BEC Насока: Cooldown не е само физическо, но и психологическо възстановяване.",
      "Дай обратна връзка кой се е справил добре и какво трябва да се подобри следващия път.",
    ],
    durationMinutes: 10,
    location: ["court", "stadium"],
    ageGroups: ["U9", "U11", "U13", "U15", "U17", "Мъже и Жени"],
    equipment: ["Ракети", "Пера"],
    intensity: 1,
    complexityLevel: 1,
    prerequisites: [],
  },
  {
    name: "Поза 'Котка и Крава' (BWF Core Stretching)",
    category: "cooldown",
    phase: "cooldown",
    source: "BWF Level 1 - Flexibility",
    description:
      "На четири крака. Извиваме гърба нагоре като ядосана котка, след това го отпускаме надолу като мързелива крава. Правим го 10 пъти много бавно.",
    coachingPoints: [
      "Разтяга гръбнака след многото скокове и навеждания.",
      "Изисквай правилно дишане (вдишване при извиване, издишване при отпускане).",
    ],
    durationMinutes: 5,
    location: ["court", "stadium"],
    ageGroups: ["U9", "U11", "U13", "U15"],
    equipment: ["Ракети", "Пера"],
    intensity: 1,
    complexityLevel: 1,
    prerequisites: [],
  },
  {
    name: "Разтягане на врата и раменете (BWF Shoulder Stretch)",
    category: "cooldown",
    phase: "cooldown",
    source: "BWF Flexibility",
    description:
      "В изправено положение, прекарваме едната ръка пред гърдите и я притискаме леко с другата. След това дърпаме лакътя зад главата. Бавно и с дълбоко дишане.",
    coachingPoints: [
      "Предотвратява мускулна треска в раменете, които са най-натоварени от ударите.",
    ],
    durationMinutes: 5,
    location: ["court", "stadium"],
    ageGroups: ["U13", "U15", "U17", "Мъже и Жени"],
    equipment: ["Ракети", "Пера"],
    intensity: 1,
    complexityLevel: 1,
    prerequisites: [],
  },
  {
    name: "Мрежа - Базово Повдигане (Net Lift Base)",
    category: "technique",
    phase: "main-tech",
    source: "BWF Level 1",
    description:
      "Подаваме на ръка от другата страна на мрежата. Детето прави крачка-тласък напред и повдига високо към задната линия.",
    coachingPoints: [
      "Ракетата трябва да посрещне перото възможно най-високо.",
      "Нападът (Lunge) завършва с петата, за да спре движението плавно.",
    ],
    durationMinutes: 10,
    location: ["court"],
    ageGroups: ["U11", "U13", "U15"],
    equipment: ["Ракети", "Пера"],
    prerequisites: [
      "Основен хват",
      "Правилен напад (Lunge)",
      "Повдигане (Lift)",
    ],
    intensity: 3,
    complexityLevel: 2,
  },
  {
    name: "Мрежа - Спиннинг Нетшот (Spinning Net Shot)",
    category: "technique",
    phase: "main-tech",
    source: "BWF Level 2",
    description:
      "Упражнение за прецизност. Подават се пера близо до филето, а играчът леко 'подрязва' перото отдолу, за да се завърти.",
    coachingPoints: [
      "Китката не трябва да прави рязко движение, а пръстите водят ракетата.",
      "Следи за отпуснат захват преди удара.",
    ],
    durationMinutes: 10,
    location: ["court"],
    ageGroups: ["U15", "U17", "U19", "Мъже и Жени"],
    equipment: ["Ракети", "Пера"],
    prerequisites: ["Основен хват", "Мрежов удар (Net Shot)"],
    intensity: 2,
    complexityLevel: 4,
  },
  {
    name: "ОФП - Стълбичка за бързина (Agility Ladder)",
    category: "physical",
    phase: "warmup",
    source: "General Fitness",
    description:
      "Различни преминавания през координационната стълбичка - вътре-вън, скиорско бягане, странични стъпки.",
    coachingPoints: [
      "Работи се на пръсти, петите не докосват земята.",
      "Ръцете работят активно като при спринт.",
    ],
    durationMinutes: 10,
    location: ["court", "stadium"],
    ageGroups: ["U11", "U13", "U15", "U17", "U19"],
    equipment: ["Стълбичка"],
    prerequisites: [],
    intensity: 4,
    complexityLevel: 2,
  },
  {
    name: "Защита - Избиване на Смач (Smash Defense Block)",
    category: "technique",
    phase: "main-tech",
    source: "BWF Level 1",
    description:
      "Треньорът прави леки смачове (или бързи драйвове), а играчът е в защитна стойка и блокира перото към мрежата.",
    coachingPoints: [
      "Стойката е широка и ниска, тежестта е леко напред.",
      "Ракетата е пред тялото, използваме предимно бекхенд хват за лявата страна и тялото.",
    ],
    durationMinutes: 15,
    location: ["court"],
    ageGroups: ["U13", "U15", "U17"],
    equipment: ["Ракети", "Пера"],
    prerequisites: ["Бекхенд хват"],
    intensity: 3,
    complexityLevel: 3,
  },
  {
    name: "Тактика - Атака срещу Защита 2v1",
    category: "tactics",
    phase: "main-tact",
    source: "BWF Level 2",
    description:
      "Двама играчи се защитават на цял корт, а един играч атакува. Атакуващият трябва да намери дупка в защитата чрез смач и дроп.",
    coachingPoints: [
      "Защитниците трябва да се движат синхронно.",
      "Атакуващият трябва да използва стръмни удари и да не бърза да завършва.",
    ],
    durationMinutes: 15,
    location: ["court"],
    ageGroups: ["U15", "U17", "U19", "Мъже и Жени"],
    equipment: ["Ракети", "Пера"],
    prerequisites: ["Смач (Smash)", "Скъсяване (Drop)", "Защита от смач"],
    intensity: 4,
    complexityLevel: 4,
  },
  {
    name: "Игри - Двойки на малък корт",
    category: "games",
    phase: "warmup",
    source: "BWF Shuttle Time",
    description:
      "Играе се само в предната част на корта (до сервис линията). Целта е да не се вдига перото.",
    coachingPoints: [
      "Бърза реакция на ракетата - дръжте я вдигната.",
      "Общувайте с партньора ('Аз', 'Ти').",
    ],
    durationMinutes: 10,
    location: ["court"],
    ageGroups: ["U11", "U13", "U15"],
    equipment: ["Ракети", "Пера"],
    prerequisites: ["Бърз драйв", "Бекхенд хват"],
    intensity: 3,
    complexityLevel: 2,
  },
  {
    name: "ОФП - Ластици за рамо",
    category: "physical",
    phase: "cooldown",
    source: "General Fitness",
    description:
      "Леки издърпвания на тренировъчни ластици за засилване на ротаторния маншон и рамото.",
    coachingPoints: [
      "Движението е бавно и контролирано.",
      "Следете лакътят да е фиксиран до тялото при външна ротация.",
    ],
    durationMinutes: 5,
    location: ["court", "stadium"],
    ageGroups: ["U13", "U15", "U17", "U19", "Мъже и Жени"],
    equipment: ["Ластици"],
    prerequisites: [],
    intensity: 2,
    complexityLevel: 1,
  },
  {
    name: "Техника - Бърз Драйв по правата",
    category: "technique",
    phase: "main-tech",
    source: "BWF Level 1",
    description:
      "Играчите са застанали от двете страни на мрежата. Разменят си бързи плоски удари (драйв) само по едната права.",
    coachingPoints: [
      "Скъсете замаха - движението идва от пръстите и китката.",
      "Следете ракетата да не пада под нивото на мрежата.",
    ],
    durationMinutes: 10,
    location: ["court"],
    ageGroups: ["U13", "U15", "U17", "U19"],
    equipment: ["Ракети", "Пера"],
    prerequisites: ["Бекхенд хват", "Плосък удар (Drive)"],
    intensity: 3,
    complexityLevel: 3,
  },
  {
    name: "Тактика - Игра 'Само в задния коридор'",
    category: "tactics",
    phase: "main-tact",
    source: "BWF Level 2",
    description:
      "Играе се на точки, но важат само пера, които падат в задния коридор (между вътрешната и външната задна линия).",
    coachingPoints: [
      "Развива усещането за дължина на клеъра и високия сервис.",
      "Следете за точен тайминг и изтласкване от краката.",
    ],
    durationMinutes: 15,
    location: ["court"],
    ageGroups: ["U13", "U15", "U17", "U19"],
    equipment: ["Ракети", "Пера"],
    prerequisites: ["Клеър (Clear)"],
    intensity: 3,
    complexityLevel: 3,
  },
  {
    name: "Разпускане - Йога Поздрав към слънцето",
    category: "cooldown",
    phase: "cooldown",
    source: "General Fitness",
    description:
      "Изпълнява се основната последователност от йога за разтягане на цялото тяло - гръбнак, крака, рамене.",
    coachingPoints: [
      "Дишането трябва да е дълбоко и синхронизирано с движенията.",
      "Задържайте във всяка позиция по 3 секунди.",
    ],
    durationMinutes: 5,
    location: ["court", "beach", "stadium"],
    ageGroups: ["U15", "U17", "U19", "Мъже и Жени"],
    equipment: [],
    prerequisites: [],
    intensity: 1,
    complexityLevel: 2,
  },
  {
    name: "Техника - Сервис от бекхенд (Backhand Short Serve)",
    category: "technique",
    phase: "warmup",
    source: "BWF Level 1",
    description:
      "Многократни повторения на къс сервис в предния сервис-квадрат.",
    coachingPoints: [
      "Палецът трябва да е изпънат на широката част на дръжката.",
      "Лявата ръка държи перото за връхчето на едно от перцата.",
    ],
    durationMinutes: 10,
    location: ["court"],
    ageGroups: ["U11", "U13", "U15", "U17", "U19"],
    equipment: ["Ракети", "Пера", "Конуси"],
    prerequisites: ["Бекхенд хват"],
    intensity: 1,
    complexityLevel: 2,
  },
  {
    name: "Тактика - Сингъл игра на 3 четвърти корт",
    category: "tactics",
    phase: "main-tact",
    source: "BWF Level 1",
    description:
      "Сингъл, при който единият коридор е забранен. Целта е да се тренира прецизност по правата и диагонала в ограничено пространство.",
    coachingPoints: [
      "Търсете откритите пространства и не играйте към центъра.",
      "Следете движението на краката след удара.",
    ],
    durationMinutes: 15,
    location: ["court"],
    ageGroups: ["U13", "U15", "U17"],
    equipment: ["Ракети", "Пера"],
    prerequisites: ["Сплит стъпка", "Правилно позициониране"],
    intensity: 4,
    complexityLevel: 3,
  },
  {
    name: "Игри - Дръж балона във въздуха",
    category: "games",
    phase: "warmup",
    source: "BWF Shuttle Time",
    description:
      "Децата трябва да тупкат балон във въздуха само с ракетите си, докато преминават от единия край на залата до другия.",
    coachingPoints: [
      "Следете децата да не се блъскат.",
      "Дръжте ракетата хоризонтално нагоре.",
    ],
    durationMinutes: 5,
    location: ["court", "stadium"],
    ageGroups: ["U9", "U11"],
    equipment: ["Ракети", "Балони"],
    prerequisites: ["Основен хват"],
    intensity: 2,
    complexityLevel: 1,
  },
  {
    name: "ОФП - Интервални Спринтове (Suicides)",
    category: "physical",
    phase: "main-tech",
    source: "General Fitness",
    description:
      "Спринт до предната сервис линия и обратно, след това до задната сервис линия и обратно, и накрая до основната задна линия и обратно.",
    coachingPoints: [
      "Докосвайте линията с ръка всеки път.",
      "Следете за бърза смяна на посоката.",
    ],
    durationMinutes: 10,
    location: ["court"],
    ageGroups: ["U15", "U17", "U19", "Мъже и Жени"],
    equipment: [],
    prerequisites: [],
    intensity: 5,
    complexityLevel: 2,
  },
  {
    name: "Техника - Смач от скок (Jump Smash)",
    category: "technique",
    phase: "main-tech",
    source: "BWF Level 2",
    description:
      "Треньорът подава високи пера, а играчът прави ножичен скок или двоен скок за максимално мощен смач.",
    coachingPoints: [
      "Лявата ръка помага за баланс и прицелване.",
      "Таймингът е най-важен - не скачайте твърде рано!",
    ],
    durationMinutes: 15,
    location: ["court"],
    ageGroups: ["U15", "U17", "U19", "Мъже и Жени"],
    equipment: ["Ракети", "Пера"],
    prerequisites: ["Смач (Smash)", "Ножичен скок"],
    intensity: 5,
    complexityLevel: 5,
  },
  {
    name: "Техника - Защита от двете страни",
    category: "technique",
    phase: "main-tech",
    source: "BWF Level 1",
    description:
      "Играчът стои в центъра. Треньорът подава пера алтернативно вляво и вдясно, играчът отговаря със защитен плосък удар.",
    coachingPoints: [
      "Придвижвайте се само с една широка крачка (Lunge) от центъра.",
      "Сменяйте хвата към бекхенд много бързо.",
    ],
    durationMinutes: 10,
    location: ["court"],
    ageGroups: ["U13", "U15", "U17"],
    equipment: ["Ракети", "Пера"],
    prerequisites: ["Шасе стъпки", "Бекхенд хват"],
    intensity: 4,
    complexityLevel: 3,
  },
  {
    name: "Тактика - Избягване на форхенда",
    category: "tactics",
    phase: "main-tact",
    source: "BWF Level 2",
    description:
      "Упражнение по двойки. Играч А може да играе където поиска, но Играч Б трябва задължително да насочва перото към бекхенда на А.",
    coachingPoints: [
      "Анализирайте как противникът се позиционира.",
      "Играйте по диагонала, ако противникът пази правата.",
    ],
    durationMinutes: 15,
    location: ["court"],
    ageGroups: ["U15", "U17", "U19"],
    equipment: ["Ракети", "Пера"],
    prerequisites: ["Контрол на насочването"],
    intensity: 4,
    complexityLevel: 4,
  },
  {
    name: "Игри - Мишена с конуси",
    category: "games",
    phase: "warmup",
    source: "BWF Shuttle Time",
    description:
      "Поставят се конуси в ъглите. Децата се редуват да сервират или да изпълняват скъсяване, за да ударят конуса.",
    coachingPoints: [
      "Концентрирайте се върху техниката, а не само върху силата.",
      "Следете изпълнението на движението на ръката да е плавно.",
    ],
    durationMinutes: 10,
    location: ["court"],
    ageGroups: ["U9", "U11", "U13"],
    equipment: ["Ракети", "Пера", "Конуси"],
    prerequisites: ["Основен хват"],
    intensity: 2,
    complexityLevel: 2,
  },
  {
    name: "ОФП - Планк с докосване на раменете",
    category: "physical",
    phase: "warmup",
    source: "General Fitness",
    description:
      "В позиция планк се докосва противоположното рамо с ръка, без да се усуква таза.",
    coachingPoints: [
      "Дръжте коремните мускули стегнати през цялото време.",
      "Тялото не трябва да се люлее наляво-надясно.",
    ],
    durationMinutes: 5,
    location: ["court", "beach", "stadium"],
    ageGroups: ["U13", "U15", "U17", "U19", "Мъже и Жени"],
    equipment: [],
    prerequisites: [],
    intensity: 3,
    complexityLevel: 2,
  },
  {
    name: "Фундамент: Основен V-образен хват (Forehand Grip)",
    category: "technique",
    phase: "warmup",
    source: "BWF Level 1",
    description:
      "Дръжте ракетата с лявата ръка за стъблото. Поставете дясната ръка върху струните и я плъзнете надолу към дръжката, сякаш се ръкувате. 'V'-образната форма между палеца и показалеца трябва да сочи към лявото рамо на рамката.",
    coachingPoints: [
      "Ръкостискане с ракетата.",
      "Хватът трябва да е отпуснат - дръжте ракетата като малка птичка.",
      "Показалецът е леко отделен от другите пръсти (спусък).",
    ],
    durationMinutes: 5,
    location: ["court", "stadium"],
    ageGroups: ["U9", "U11", "U13", "U15", "U17", "U19", "Мъже и Жени"],
    equipment: ["Ракети"],
    prerequisites: [],
    intensity: 1,
    complexityLevel: 1,
  },
  {
    name: "Фундамент: Бекхенд хват (Thumb Grip)",
    category: "technique",
    phase: "warmup",
    source: "BWF Level 1",
    description:
      "Завъртете ракетата леко навътре спрямо основния хват. Палецът трябва да бъде изпънат и да лежи плоско върху най-широката част (плоската страна) на дръжката.",
    coachingPoints: [
      "Палецът натиска плоската част за сила при бекхенд удари.",
      "Останалите пръсти са отпуснати.",
      "Има малко пространство между дръжката и дланта (ракетата се държи с пръстите).",
    ],
    durationMinutes: 5,
    location: ["court", "stadium"],
    ageGroups: ["U9", "U11", "U13", "U15", "U17", "U19", "Мъже и Жени"],
    equipment: ["Ракети"],
    prerequisites: [],
    intensity: 1,
    complexityLevel: 1,
  },
  {
    name: "Фундамент: Хват 'Тиган' (Panhandle Grip)",
    category: "technique",
    phase: "warmup",
    source: "BWF Level 1",
    description:
      "Хват за специфични удари (най-често бърз драйв и късни удари на мрежата). Вземете ракетата така, че рамката да е успоредна на пода, сякаш държите тиган.",
    coachingPoints: [
      "V-формата се премества върху широката, горна част на дръжката.",
      "Палецът почива леко отстрани, не отдолу.",
      "Използва се основно за натискане (Push) към мрежата.",
    ],
    durationMinutes: 5,
    location: ["court", "stadium"],
    ageGroups: ["U9", "U11", "U13", "U15", "U17", "U19", "Мъже и Жени"],
    equipment: ["Ракети"],
    prerequisites: [],
    intensity: 1,
    complexityLevel: 1,
  },
  {
    name: "Фундамент: Основна стойка за готовност (Ready Position)",
    category: "technique",
    phase: "warmup",
    source: "BWF Level 1",
    description:
      "Застанете в центъра на корта. Краката са на ширината на раменете. Тежестта е леко напред върху възглавничките на стъпалата. Коленете са леко свити.",
    coachingPoints: [
      "Ракетата се държи пред тялото на нивото на гърдите.",
      "Свободната ръка помага за баланс.",
      "Дръжте основен хват в готовност.",
    ],
    durationMinutes: 5,
    location: ["court"],
    ageGroups: ["U9", "U11", "U13", "U15", "U17", "U19", "Мъже и Жени"],
    equipment: ["Ракети"],
    prerequisites: ["Основен хват"],
    intensity: 1,
    complexityLevel: 1,
  },
  {
    name: "Фундамент: Защитна стойка (Defensive Stance)",
    category: "technique",
    phase: "warmup",
    source: "BWF Level 2",
    description:
      "Използва се при защита от смач. По-широк разкрач от нормалния. Центърът на тежестта е по-ниско. Ракетата е вдигната пред тялото с бекхенд хват.",
    coachingPoints: [
      "Краката са успоредни един на друг.",
      "Ракетата трябва да е пред тялото, готова за блокиране.",
      "Погледът е фокусиран върху ракетата на противника.",
    ],
    durationMinutes: 5,
    location: ["court"],
    ageGroups: ["U11", "U13", "U15", "U17", "U19", "Мъже и Жени"],
    equipment: ["Ракети"],
    prerequisites: ["Бекхенд хват"],
    intensity: 2,
    complexityLevel: 2,
  },
  {
    name: "Фундамент: Стойка за посрещане на сервис (Receiving Stance)",
    category: "technique",
    phase: "warmup",
    source: "BWF Level 1",
    description:
      "Лявата нога е напред (за играещи с дясна ръка). Ракетата е вдигната пред тялото. Тежестта е предимно на предния крак, готови за старт.",
    coachingPoints: [
      "Ракетата да не закрива очите.",
      "Задният крак е леко повдигнат на пръсти за бързо изтласкване.",
      "Концентрация върху ръката на сервиращия.",
    ],
    durationMinutes: 5,
    location: ["court"],
    ageGroups: ["U9", "U11", "U13", "U15", "U17", "U19", "Мъже и Жени"],
    equipment: ["Ракети"],
    prerequisites: ["Основен хват"],
    intensity: 1,
    complexityLevel: 1,
  },
  {
    name: "Фундамент: Сплит Стъпка (Split Drop / Split Step)",
    category: "technique",
    phase: "main-tech",
    source: "BWF Level 1",
    description:
      "Леко подскокване преди всеки удар на противника. Приземяването става в момента, в който противникът удря перото. Краката се разтварят леко за стабилност.",
    coachingPoints: [
      "Таймингът е ключов - приземете се В МОМЕНТА на удара.",
      "Не скачайте високо, само разтворете краката.",
      "Приземяване на възглавничките на стъпалата за експлозивен старт.",
    ],
    durationMinutes: 10,
    location: ["court"],
    ageGroups: ["U11", "U13", "U15", "U17", "U19", "Мъже и Жени"],
    equipment: ["Ракети"],
    prerequisites: ["Основна стойка за готовност"],
    intensity: 3,
    complexityLevel: 3,
  },
  {
    name: "Фундамент: Шасе стъпки (Chasse Steps)",
    category: "technique",
    phase: "main-tech",
    source: "BWF Level 1",
    description:
      "Странично придвижване без кръстосване на краката. Задният крак 'гони' предния, като почти го докосва, преди предният крак да стъпи отново.",
    coachingPoints: [
      "Пазете центъра на тежестта ниско.",
      "Използвайте ги за къси и средни разстояния.",
      "Не кръстосвайте краката - така запазвате баланс.",
    ],
    durationMinutes: 10,
    location: ["court"],
    ageGroups: ["U9", "U11", "U13", "U15", "U17", "U19", "Мъже и Жени"],
    equipment: ["Ракети"],
    prerequisites: [],
    intensity: 2,
    complexityLevel: 2,
  },
  {
    name: "Фундамент: Правилен Напад (Lunge)",
    category: "technique",
    phase: "main-tech",
    source: "BWF Level 1",
    description:
      "Последната крачка към мрежата с водещия крак (десния). Стъпването започва от петата и се пренася към пръстите.",
    coachingPoints: [
      "Коляното не трябва да преминава пред линията на пръстите на крака.",
      "Задният крак се плъзга леко по пода с вътрешната си страна.",
      "Ударът се извършва едновременно с приземяването на петата.",
    ],
    durationMinutes: 10,
    location: ["court"],
    ageGroups: ["U9", "U11", "U13", "U15", "U17", "U19", "Мъже и Жени"],
    equipment: ["Ракети"],
    prerequisites: [],
    intensity: 3,
    complexityLevel: 2,
  },
  {
    name: "Фундамент: Ножичен отскок (Scissor Jump)",
    category: "technique",
    phase: "main-tech",
    source: "BWF Level 2",
    description:
      "Използва се при удари над главата в задната част на корта. Дясната нога е назад, скачате, удряте перото във въздуха и сменяте краката - приземявате се на десния крак, а левият отива назад за баланс.",
    coachingPoints: [
      "Ротацията на таза е ключова за генериране на сила.",
      "Приземяването е плавно и меко, последвано от бързо изтласкване напред.",
    ],
    durationMinutes: 15,
    location: ["court"],
    ageGroups: ["U13", "U15", "U17", "U19", "Мъже и Жени"],
    equipment: ["Ракети"],
    prerequisites: ["Сплит Стъпка", "Движение за удар над главата"],
    intensity: 4,
    complexityLevel: 4,
  },
  {
    name: "Фундамент: Кръстосана стъпка (Cross-over Step)",
    category: "technique",
    phase: "main-tech",
    source: "BWF Level 2",
    description:
      "Бързо придвижване към дълбок бекхенд или форхенд ъгъл. Десният крак кръстосва левия (или обратно) за покриване на максимално разстояние с минимален брой стъпки.",
    coachingPoints: [
      "Първата стъпка задава посоката.",
      "Торсът остава стабилен.",
      "Завършва винаги с правилен напад (Lunge).",
    ],
    durationMinutes: 10,
    location: ["court"],
    ageGroups: ["U13", "U15", "U17", "U19", "Мъже и Жени"],
    equipment: ["Ракети"],
    prerequisites: ["Правилен Напад (Lunge)"],
    intensity: 3,
    complexityLevel: 3,
  },
  {
    name: "Фундамент: Движение за удар над главата (Overhead Throwing Action)",
    category: "technique",
    phase: "main-tech",
    source: "BWF Level 1",
    description:
      "Биомеханика на форхенда: Ракетата пада зад гърба (бексуинг). Движението започва от ротация на бедрата, следвано от рамото, лакътя (сочещ нагоре) и завършва с пронация на предмишницата (завъртане).",
    coachingPoints: [
      "Имитирайте хвърляне на топка.",
      "Лявата ръка сочи към перото.",
      "Ударът е пред тялото и високо.",
    ],
    durationMinutes: 15,
    location: ["court"],
    ageGroups: ["U11", "U13", "U15", "U17", "U19", "Мъже и Жени"],
    equipment: ["Ракети"],
    prerequisites: ["Основен хват"],
    intensity: 3,
    complexityLevel: 4,
  },
  {
    name: "Фундамент: Къс Бекхенд Сервис (Short Backhand Serve)",
    category: "technique",
    phase: "warmup",
    source: "BWF Level 1",
    description:
      "Сервис в предния квадрат. Десният крак е напред. Бекхенд хват. Перото се държи за перата и се изтласква леко с палеца над мрежата.",
    coachingPoints: [
      "Тежестта се прехвърля леко от задния на предния крак.",
      "Движението на ракетата е много късо, идващо от лакътя и китката.",
      "Не вдигайте лакътя над рамото.",
    ],
    durationMinutes: 10,
    location: ["court"],
    ageGroups: ["U9", "U11", "U13", "U15", "U17", "U19", "Мъже и Жени"],
    equipment: ["Ракети", "Пера"],
    prerequisites: ["Бекхенд хват", "Стойка за посрещане на сервис"],
    intensity: 1,
    complexityLevel: 2,
  },
  {
    name: "Фундамент: Висок Форхенд Сервис (High Forehand Serve)",
    category: "technique",
    phase: "warmup",
    source: "BWF Level 1",
    description:
      "Сервис за сингъл. Широк замах отдолу нагоре. Тежестта преминава от задния на предния крак, перото лети високо и дълбоко към задната линия.",
    coachingPoints: [
      "Дръжте перото високо пред себе си.",
      "Следете движението (follow-through) на ракетата над противоположното рамо.",
      "Ударната точка трябва да е под кръста.",
    ],
    durationMinutes: 10,
    location: ["court"],
    ageGroups: ["U9", "U11", "U13", "U15", "U17", "U19", "Мъже и Жени"],
    equipment: ["Ракети", "Пера"],
    prerequisites: ["Основен хват"],
    intensity: 2,
    complexityLevel: 2,
  },
  {
    name: "Фундамент: Клеър (Clear)",
    category: "technique",
    phase: "main-tech",
    source: "BWF Level 1",
    description:
      "Удар от задна до задна линия. Целта е да оттласне противника. Контактът с перото е възможно най-високо и леко пред тялото.",
    coachingPoints: [
      "Задължително пълно движение над главата.",
      "Перото трябва да има висока траектория.",
      "Бързо връщане в центъра след удара.",
    ],
    durationMinutes: 10,
    location: ["court"],
    ageGroups: ["U11", "U13", "U15", "U17", "U19", "Мъже и Жени"],
    equipment: ["Ракети", "Пера"],
    prerequisites: ["Движение за удар над главата", "Ножичен отскок"],
    intensity: 3,
    complexityLevel: 3,
  },
  {
    name: "Фундамент: Смач (Smash) - Основи",
    category: "technique",
    phase: "main-tech",
    source: "BWF Level 2",
    description:
      "Атакуващ удар надолу. Контактът с перото е малко по-напред отколкото при клеъра. Движението е експлозивно с рязко ускорение на главата на ракетата.",
    coachingPoints: [
      "Използвайте пронация на предмишницата за максимална сила.",
      "Ъгълът на ракетата е насочен стръмно надолу.",
      "Таймингът е по-важен от мускулната сила.",
    ],
    durationMinutes: 15,
    location: ["court"],
    ageGroups: ["U13", "U15", "U17", "U19", "Мъже и Жени"],
    equipment: ["Ракети", "Пера"],
    prerequisites: ["Движение за удар над главата", "Клеър (Clear)"],
    intensity: 4,
    complexityLevel: 4,
  },
  {
    name: "Фундамент: Скъсяване (Drop Shot) - Основи",
    category: "technique",
    phase: "main-tech",
    source: "BWF Level 1",
    description:
      "Удар от задна линия, който пада близо до мрежата от другата страна. Подготовката е същата като за клеър/смач, за да заблуди противника.",
    coachingPoints: [
      "Скоростта на ръката се забавя точно преди контакта.",
      "Замахът не спира рязко, а продължава плавно.",
      "Контактът е леко пред тялото.",
    ],
    durationMinutes: 10,
    location: ["court"],
    ageGroups: ["U11", "U13", "U15", "U17", "U19", "Мъже и Жени"],
    equipment: ["Ракети", "Пера"],
    prerequisites: ["Движение за удар над главата"],
    intensity: 2,
    complexityLevel: 3,
  },
  {
    name: "Фундамент: Мрежов удар (Net Shot / Hairpin)",
    category: "technique",
    phase: "main-tech",
    source: "BWF Level 1",
    description:
      "Тънък и прецизен удар от мрежа към мрежа. Посрещнете перото високо, ракетата насочва перото с леко движение нагоре и напред.",
    coachingPoints: [
      "Водете движението с ракетата, кракът стъпва (Lunge) заедно с удара.",
      "Китката е стегната, но хватът е мек.",
      "Ракетата не пада под филето след удара.",
    ],
    durationMinutes: 10,
    location: ["court"],
    ageGroups: ["U9", "U11", "U13", "U15", "U17", "U19", "Мъже и Жени"],
    equipment: ["Ракети", "Пера"],
    prerequisites: ["Правилен Напад (Lunge)", "Основен хват", "Бекхенд хват"],
    intensity: 2,
    complexityLevel: 3,
  },
  {
    name: "Фундамент: Плосък удар (Drive)",
    category: "technique",
    phase: "main-tech",
    source: "BWF Level 2",
    description:
      "Бърз, плосък удар над мрежата. Замахът е много къс, използва се оттласкване от пръстите и предмишницата (Snap).",
    coachingPoints: [
      "Ракетата винаги се държи пред тялото.",
      "Използва се предимно хват 'Тиган' или Бекхенд хват в зависимост от страната.",
      "Без голям замах от рамото.",
    ],
    durationMinutes: 10,
    location: ["court"],
    ageGroups: ["U11", "U13", "U15", "U17", "U19", "Мъже и Жени"],
    equipment: ["Ракети", "Пера"],
    prerequisites: ["Хват 'Тиган' (Panhandle Grip)", "Бекхенд хват"],
    intensity: 3,
    complexityLevel: 3,
  },
  {
    name: "Фундамент: Отразяване на смач (Smash Defense / Defense Block)",
    category: "technique",
    phase: "main-tech",
    source: "BWF Level 2",
    description:
      "Ниска защитна стойка. Готовност с бекхенд хват пред гърдите. 'Омекотяване' или 'повдигане' на перото с късо движение на китката.",
    coachingPoints: [
      "Използвайте бекхенд хват за цялата част пред тялото.",
      "Ракетата трябва да посрещне перото далеч пред тялото, за да абсорбира силата.",
      "Погледът следи ракетата на противника, а не перото.",
    ],
    durationMinutes: 10,
    location: ["court"],
    ageGroups: ["U13", "U15", "U17", "U19", "Мъже и Жени"],
    equipment: ["Ракети", "Пера"],
    prerequisites: ["Защитна стойка (Defensive Stance)", "Бекхенд хват"],
    intensity: 3,
    complexityLevel: 4,
  },
  {
    name: "Фундамент: Удар около главата (Round-the-Head Stroke)",
    category: "technique",
    phase: "main-tech",
    source: "BWF Level 2",
    description:
      "Алтернативата на задния бекхенд. Придвижване към бекхенд ъгъла и замах с форхенд НАД главата, докато тялото се извива назад.",
    coachingPoints: [
      "Десният крак се изтегля далеч назад (за десничари).",
      "Ракетата се движи по 'орбита' около лявата страна на главата.",
      "Бързо връщане с ножичен отскок към центъра.",
    ],
    durationMinutes: 15,
    location: ["court"],
    ageGroups: ["U13", "U15", "U17", "U19", "Мъже и Жени"],
    equipment: ["Ракети", "Пера"],
    prerequisites: [
      "Движение за удар над главата",
      "Ножичен отскок (Scissor Jump)",
    ],
    intensity: 4,
    complexityLevel: 5,
  },
  {
    name: "Фундамент: Възстановяване след Напад (Recovery Step from Net)",
    category: "technique",
    phase: "main-tech",
    source: "BWF Level 1",
    description:
      "Рязко избутващо движение с предния крак за бързо връщане към центъра ВЕДНАГА след извършване на мрежов удар.",
    coachingPoints: [
      "Изтласкването става главно от петата и бедрото на водещия крак.",
      "Не се обръщайте с гръб към мрежата.",
      "Веднага след изтласкването сте готови за Сплит Стъпка.",
    ],
    durationMinutes: 10,
    location: ["court"],
    ageGroups: ["U9", "U11", "U13", "U15", "U17", "U19", "Мъже и Жени"],
    equipment: ["Ракети"],
    prerequisites: ["Правилен Напад (Lunge)", "Сплит Стъпка (Split Drop)"],
    intensity: 3,
    complexityLevel: 2,
  },
  {
    name: "Фундамент: Завършване на мрежата (Net Kill / Rush)",
    category: "technique",
    phase: "main-tech",
    source: "BWF Level 2",
    description:
      "Прихващане на перото високо над нивото на филето с бързо 'натискане' или отсечен удар. Придвижването към мрежата трябва да е агресивно.",
    coachingPoints: [
      "Ракетата не бива да замахва силно, за да не се удари в мрежата (фаул).",
      "Движението идва само от стискане на пръстите и леко свиване на китката.",
      "Използвайте Хват Тиган (Panhandle) или Бекхенд според страната.",
    ],
    durationMinutes: 10,
    location: ["court"],
    ageGroups: ["U13", "U15", "U17", "U19", "Мъже и Жени"],
    equipment: ["Ракети", "Пера"],
    prerequisites: ["Хват 'Тиган' (Panhandle Grip)", "Правилен Напад (Lunge)"],
    intensity: 4,
    complexityLevel: 3,
  },
  {
    name: "Схема: Клеър -> Напад -> Възстановяване",
    category: "tactics",
    phase: "main-tact",
    source: "BWF Routine",
    description:
      "Трениращият изпълнява дълбок клеър от задна линия, след което веднага прави бързо придвижване (спринт) напред и завършва с напад и мрежов удар. Незабавно възстановяване в центъра след удара на мрежата.",
    coachingPoints: [
      "Рязко спиране на предната линия и изтласкване от петата след мрежовия удар.",
      "Мрежовият удар трябва да е максимално прецизен.",
      "Таймингът на сплит стъпката трябва да съвпада с удара на подавача.",
    ],
    durationMinutes: 15,
    location: ["court"],
    ageGroups: ["U13", "U15", "U17", "U19", "Мъже и Жени"],
    equipment: ["Ракети", "Пера"],
    prerequisites: [
      "Клеър (Clear)",
      "Правилен Напад (Lunge)",
      "Възстановяване след Напад (Recovery Step from Net)",
    ],
    intensity: 4,
    complexityLevel: 3,
  },
  {
    name: "Схема: Драйв отбрана на мрежата",
    category: "tactics",
    phase: "main-tact",
    source: "BWF Routine",
    description:
      "Двама играчи застават един срещу друг на сервиз линията. Играят се само бързи, плоски удари (Drives). Целта е да не се вдига перото. Движението е минимално, работи се предимно с предмишница и пръсти.",
    coachingPoints: [
      "Ракетата трябва да е ВИНАГИ пред тялото.",
      "Хват 'Тиган' (Panhandle) за форхенд, палец за бекхенд.",
      "Минимален замах, бърз рефлекс.",
    ],
    durationMinutes: 10,
    location: ["court"],
    ageGroups: ["U11", "U13", "U15", "U17", "U19", "Мъже и Жени"],
    equipment: ["Ракети", "Пера"],
    prerequisites: ["Плосък удар (Drive)"],
    intensity: 3,
    complexityLevel: 3,
  },
  {
    name: "Схема: Смач и последващ мрежов кил",
    category: "tactics",
    phase: "main-tact",
    source: "BWF Routine",
    description:
      "Подавачът вдига високо перо. Играчът атакува със силен смач. Подавачът 'отразява' с къс удар на мрежата. Играчът се придвижва експлозивно и завършва с Net Kill.",
    coachingPoints: [
      "Веднага след смача, тежестта пада напред за спринт.",
      "Не спирайте да следите перото след смача.",
      "Завършването на мрежата е с късо натискане, без замах (за да не докоснете филето).",
    ],
    durationMinutes: 15,
    location: ["court"],
    ageGroups: ["U15", "U17", "U19", "Мъже и Жени"],
    equipment: ["Ракети", "Пера"],
    prerequisites: [
      "Смач (Smash) - Основи",
      "Завършване на мрежата (Net Kill / Rush)",
    ],
    intensity: 5,
    complexityLevel: 4,
  },
  {
    name: "Решения: Атака срещу защита 2v1",
    category: "tactics",
    phase: "main-tact",
    source: "BWF Tactical",
    description:
      "Двама подавачи защитават цял корт (в защитна стойка). Един играч атакува с клеър или смач, след което избира дали да скъси или да атакува отново. Подавачите връщат къде да е.",
    coachingPoints: [
      "Атакуващият трябва да мести защитниците, а не да бие в тях.",
      "Следене на празните пространства.",
      "Избор на правилния момент за смач.",
    ],
    durationMinutes: 20,
    location: ["court"],
    ageGroups: ["U15", "U17", "U19", "Мъже и Жени"],
    equipment: ["Ракети", "Пера"],
    prerequisites: ["Скъсяване (Drop Shot) - Основи"],
    intensity: 4,
    complexityLevel: 5,
  },
  {
    name: "Решения: Избор на мрежата (Push или Lift)",
    category: "tactics",
    phase: "main-tact",
    source: "BWF Tactical",
    description:
      "Подавачът подава къси пера на мрежата. Играчът пристъпва с напад. В последния момент подавачът се придвижва леко напред (сигнал за Lift) или остава назад (сигнал за Push). Играчът трябва да реагира визуално.",
    coachingPoints: [
      "Периферно зрение - следете не само перото, но и подавача.",
      "Дръжте ракетата високо, за да имате повече опции.",
      "Маскирайте удара до последно.",
    ],
    durationMinutes: 15,
    location: ["court"],
    ageGroups: ["U13", "U15", "U17", "U19", "Мъже и Жени"],
    equipment: ["Ракети", "Пера"],
    prerequisites: ["Мрежов удар (Net Shot / Hairpin)"],
    intensity: 3,
    complexityLevel: 5,
  },
  {
    name: "Игра с условия: Half-court Singles (Половин корт)",
    category: "games",
    phase: "main-tact",
    source: "BWF Games",
    description:
      "Игра на единично, но само върху едната надлъжна половина на корта (включително коридорите за двойки, ако желаете). Целта е изграждане на търпение и издръжливост без резки смени на посоката.",
    coachingPoints: [
      "Фокус върху контрол на дължината (от мрежата до задна линия).",
      "Избягвайте грешки от нетърпение.",
      "Идеално за загряваща игра (Conditioned Game).",
    ],
    durationMinutes: 20,
    location: ["court"],
    ageGroups: ["U11", "U13", "U15", "U17", "U19", "Мъже и Жени"],
    equipment: ["Ракети", "Пера"],
    prerequisites: [],
    intensity: 4,
    complexityLevel: 3,
  },
  {
    name: "Игра с условия: Smash-to-Score",
    category: "games",
    phase: "main-tact",
    source: "BWF Games",
    description:
      "Редовна игра на сингъл или двойки, но точки се отбелязват САМО ако печелившият удар е Смач или Завършване на мрежата (Net Kill). Ако противникът сгреши от друг удар, не се дава точка, а само сервис.",
    coachingPoints: [
      "Принуждава играчите да търсят атака и да изграждат възможности.",
      "Тренира защитата (да не даваме високо перо).",
      "Стимулира агресивността пред мрежата.",
    ],
    durationMinutes: 20,
    location: ["court"],
    ageGroups: ["U13", "U15", "U17", "U19", "Мъже и Жени"],
    equipment: ["Ракети", "Пера"],
    prerequisites: ["Смач (Smash) - Основи"],
    intensity: 5,
    complexityLevel: 4,
  },
  {
    name: "Игра с условия: Front vs Back Court",
    category: "games",
    phase: "main-tact",
    source: "BWF Games",
    description:
      "Единият играч има право да удря перото само от задната половина (всичко пред сервиз линията е аут за него). Другият играе само на мрежата (всичко зад късия сервиз е аут за него).",
    coachingPoints: [
      "Тренира изключителна прецизност при късите удари и вдиганията.",
      "Играчът отзад развива смач и скъсяване.",
      "Играчът отпред тренира бързи реакции и блокове.",
    ],
    durationMinutes: 15,
    location: ["court"],
    ageGroups: ["U13", "U15", "U17", "U19", "Мъже и Жени"],
    equipment: ["Ракети", "Пера"],
    prerequisites: [],
    intensity: 3,
    complexityLevel: 4,
  },
  {
    name: "Тактика Сингъл: Пирамида на позициониране (Връщане в Базата)",
    category: "tactics",
    phase: "main-tact",
    source: "BWF Tactics",
    description:
      "Многоперково упражнение (Multi-shuttle). Треньорът подава пера в 4-те ъгъла. Играчът е ЗАДЪЛЖЕН след всеки удар да се върне в централната 'база' и да направи Сплит стъпка, преди да тръгне към следващото перо.",
    coachingPoints: [
      "Базата не е винаги геометричният център - тя се измества леко според удара.",
      "Без мързел - връщането трябва да е бързо (Recovery Step).",
      "Ракетата трябва да е в готовност веднага щом стъпите в базата.",
    ],
    durationMinutes: 20,
    location: ["court"],
    ageGroups: ["U13", "U15", "U17", "U19", "Мъже и Жени"],
    equipment: ["Ракети", "Пера"],
    prerequisites: ["Сплит Стъпка (Split Drop / Split Step)"],
    intensity: 5,
    complexityLevel: 4,
  },
  {
    name: "Тактика Сингъл: Натиск в 4-те ъгъла (4-Corner Drill)",
    category: "tactics",
    phase: "main-tact",
    source: "BWF Tactics",
    description:
      "Играчът играе срещу треньор/опонент, като е инструктиран да насочва перото последователно в 4-те крайни ъгъла на корта. Целта е да раздвижи максимално опонента и да създаде умора (изтощаване).",
    coachingPoints: [
      "Търсете максимална дълбочина и ширина.",
      "Не бързайте със завършващ удар - градете атаката.",
      "Използвайте Клеър и Скъсяване за манипулиране на темпото.",
    ],
    durationMinutes: 15,
    location: ["court"],
    ageGroups: ["U15", "U17", "U19", "Мъже и Жени"],
    equipment: ["Ракети", "Пера"],
    prerequisites: [],
    intensity: 4,
    complexityLevel: 4,
  },
  {
    name: "Тактика Двойки: Атакуваща ротация (Пред-Зад)",
    category: "tactics",
    phase: "main-tact",
    source: "BWF Tactics",
    description:
      "Тренировка за преминаване от защитна формация (един до друг) към атакуваща (един пред друг). Когато двойката е в защита и единият успее да натисне перото надолу (блок/смач), той продължава напред към мрежата, а партньорът му минава зад него.",
    coachingPoints: [
      "Ключът е в удара надолу - той е сигнал за ротация.",
      "Партньорът отзад трябва да е готов за смач.",
      "Комуникация: 'Аз съм пред' / 'Мое'.",
    ],
    durationMinutes: 20,
    location: ["court"],
    ageGroups: ["U15", "U17", "U19", "Мъже и Жени"],
    equipment: ["Ракети", "Пера"],
    prerequisites: ["Отразяване на смач (Smash Defense / Defense Block)"],
    intensity: 4,
    complexityLevel: 5,
  },
  {
    name: "Тактика Двойки: Покриване на зони в защита",
    category: "tactics",
    phase: "main-tact",
    source: "BWF Tactics",
    description:
      "Упражнение за защитната формация на двойки. Когато двойката повдигне перото (Lift), двамата играчи веднага застават успоредно (един до друг). Всеки покрива своята половина от корта. Треньорът подава смачове към различни зони.",
    coachingPoints: [
      "Ротация на таза и ракетите пред тялото (Защитна стойка).",
      "При смач в средата, играчът с форхенд към средата поема удара (или според предварителна уговорка).",
      "Целта на защитата е да насочи перото към празно пространство.",
    ],
    durationMinutes: 15,
    location: ["court"],
    ageGroups: ["U13", "U15", "U17", "U19", "Мъже и Жени"],
    equipment: ["Ракети", "Пера"],
    prerequisites: ["Защитна стойка (Defensive Stance)"],
    intensity: 3,
    complexityLevel: 4,
  },
  {
    name: "Тактика Двойки/Смесени: Първите 3 удара",
    category: "tactics",
    phase: "main-tact",
    source: "BWF Tactics",
    description:
      "Тренира се само Сервис -> Посрещане -> Трети удар. Разиграването спира след 3-тия удар. Фокус върху къс и агресивен сервис, агресивно посрещане (натиск) и светкавична реакция на сервиращия.",
    coachingPoints: [
      "Сервиращият НЕ се отдръпва назад след сервиса, а пази мрежата (особено в смесени двойки).",
      "Посрещачът трябва да е експлозивен и да търси удари надолу.",
      "Всичко зависи от милисекунди реакция - дръжте ракетите високо.",
    ],
    durationMinutes: 15,
    location: ["court"],
    ageGroups: ["U15", "U17", "U19", "Мъже и Жени"],
    equipment: ["Ракети", "Пера"],
    prerequisites: [
      "Къс Бекхенд Сервис (Short Backhand Serve)",
      "Стойка за посрещане на сервис (Receiving Stance)",
    ],
    intensity: 4,
    complexityLevel: 4,
  },
  {
    name: "Сянка с ракета (Shadow Badminton) с треньор",
    category: "physical",
    phase: "warmup",
    source: "BWF Conditioning",
    description:
      "Треньорът посочва един от 6-те ъгъла (4-те крайни и 2 странични). Играчът изпълнява експлозивно придвижване към съответния ъгъл, имитира пълен удар (Shadow) и се връща в базата.",
    coachingPoints: [
      "Техниката на стъпките е по-важна от скоростта.",
      "Дръжте правилен хват.",
      "Сплит стъпка в базата при всяко връщане.",
    ],
    durationMinutes: 15,
    location: ["court"],
    ageGroups: ["U11", "U13", "U15", "U17", "U19", "Мъже и Жени"],
    equipment: ["Ракети"],
    prerequisites: ["Сплит Стъпка (Split Drop / Split Step)"],
    intensity: 4,
    complexityLevel: 3,
  },
  {
    name: "Стълбичка за бързина: Интервали",
    category: "physical",
    phase: "warmup",
    source: "BWF Conditioning",
    description:
      "10 рунда по координационна стълбичка. Смяна на упражненията: вътре-вън, странично, скиорско, високо коляно. Акцент върху бързина на краката и синхрон с ръцете.",
    coachingPoints: [
      "Контакт само с предната част на стъпалото (възглавничките).",
      "Ръцете работят активно като при спринт.",
      "Не гледайте в краката си, вдигнете брадичката.",
    ],
    durationMinutes: 10,
    location: ["court", "stadium"],
    ageGroups: ["U9", "U11", "U13", "U15", "U17", "U19", "Мъже и Жени"],
    equipment: ["Стълбичка"],
    prerequisites: [],
    intensity: 4,
    complexityLevel: 2,
  },
  {
    name: "Спринтове с ластици за експлозивност",
    category: "physical",
    phase: "main-tech",
    source: "BWF Conditioning",
    description:
      "Единият играч слага ластик около кръста, другият го държи и оказва съпротивление. Първият спринтира напред (имитация на напад към мрежата) срещу съпротивлението. Смяна след 10 повторения.",
    coachingPoints: [
      "Мощно изтласкване от петата.",
      "Запазване на права стойка на торса.",
      "Работи се за експлозивна сила.",
    ],
    durationMinutes: 15,
    location: ["court", "stadium"],
    ageGroups: ["U15", "U17", "U19", "Мъже и Жени"],
    equipment: ["Ластици"],
    intensity: 5,
    complexityLevel: 2,
  },
  {
    name: "1. Тест: Шампион по правилата на Бадминтона (BWF Основи)",
    category: "quiz",
    phase: "main-tact",
    source: "BWF Laws & Rules",
    description:
      "Интерактивна викторина и тест за основните правила на бадминтона: височина на сервиса, размери на корта (единично/двойки), система за точкуване (до 21 точки) и често срещани съдийски ситуации.",
    coachingPoints: [
      "Разясняване на линиите за сервис и разиграване при единично и двойки.",
      "Правило за контакт с перото под височината на талията (1.15м).",
      "Обяснение на ситуации с 'Let' (повторение на разиграването).",
    ],
    durationMinutes: 15,
    location: ["court", "stadium"],
    ageGroups: ["U9", "U11", "U13", "U15", "U17", "U19", "Мъже и Жени"],
    equipment: ["Тест / Въпросник"],
    intensity: 1,
    complexityLevel: 1,
  },
  {
    name: "2. Тест: Майстор на кортовете и геометрия на ударите",
    category: "quiz",
    phase: "main-tact",
    source: "BWF Tactical Awareness",
    description:
      "Теоретичен тест за зоните на корта (предна, средна, задна), траектория на перото (Clear, Drop, Smash, Net shot, Lift) и тактическо позициониране след удар (Base position).",
    coachingPoints: [
      "Разпознаване на 4-те ъгъла на корта и централната базова позиция.",
      "Разлика между атакуващ и защитен клиър/дроп.",
    ],
    durationMinutes: 15,
    location: ["court", "stadium"],
    ageGroups: ["U9", "U11", "U13", "U15", "U17", "U19", "Мъже и Жени"],
    equipment: ["Тест / Въпросник"],
    intensity: 1,
    complexityLevel: 1,
  },
  {
    name: "3. Тест: Съдийство, Сигнализация и Грешки (BWF Faults)",
    category: "quiz",
    phase: "main-tact",
    source: "BWF Umpire Guide",
    description:
      "Тест за разпознаване на съдийски сигнали и грешки (Faults): двойно докосване, докосване на мрежата с ракета/тяло, застъпване на линии при сервис и престъпване.",
    coachingPoints: [
      "Какво да правим при спорна топка.",
      "Официални жестове на главен съдия и съдии на линии.",
    ],
    durationMinutes: 15,
    location: ["court", "stadium"],
    ageGroups: ["U11", "U13", "U15", "U17", "U19", "Мъже и Жени"],
    equipment: ["Тест / Въпросник"],
    intensity: 1,
    complexityLevel: 2,
  },
  {
    name: "4. Тест: Тактика и Ротация при Двойки и Смесени двойки",
    category: "quiz",
    phase: "main-tact",
    source: "BWF Doubles Tactics",
    description:
      "Теоретична викторина за формациите при игра по двойки: Нападателна формация (отпред-отзад) срещу Защитна формация (ляво-дясно) и преход между тях.",
    coachingPoints: [
      "Разпределение на зоните между партньорите при смесени двойки (микс).",
      "Кой покрива средата на корта.",
    ],
    durationMinutes: 20,
    location: ["court", "stadium"],
    ageGroups: ["U13", "U15", "U17", "U19", "Мъже и Жени"],
    equipment: ["Тест / Въпросник"],
    intensity: 1,
    complexityLevel: 2,
  },
  {
    name: "5. Вътрешен правилник, Дисциплина и Спортна етика",
    category: "quiz",
    phase: "warmup",
    source: "Клубен Кодекс & BWF Fair Play",
    description:
      "Теоретична дискусия и въпросник относно спазването на лагерната дисциплина, режима на сън и хранене, отношението към съотборниците, съперниците и треньорите.",
    coachingPoints: [
      "Честна игра (Fair Play) и спортсменско поведение на корта и извън него.",
      "Правила за безопасност и пазене на клубната екипировка и инвентар.",
    ],
    durationMinutes: 15,
    location: ["court", "stadium"],
    ageGroups: ["U9", "U11", "U13", "U15", "U17", "U19", "Мъже и Жени"],
    equipment: [],
    intensity: 1,
    complexityLevel: 1,
  },
];
