import { Exercise } from "@/types/planner.types";

export const CAMP_EXERCISES: Omit<
  Exercise,
  "id" | "siteId" | "createdAt" | "updatedAt"
>[] = [
  // AEROBIC ENDURANCE (CROSS RUNS)
  {
    name: "Крос - 10 минути (Въвеждащ)",
    description:
      "Аеробно бягане с ниска до умерена интензивност. Използва се за възстановяване или лека загрявка на лагери.",
    category: "physical",
    source: "BWF Coach Level 1 / Badminton Europe Camp Protocol",
    location: ["outdoor"],
    ageGroups: ["U11", "U13", "U15", "U17", "U19", "Мъже и Жени"],
    durationMinutes: 10,
    equipment: "Спортен екип, Хронометър",
    focusTags: ["лагер", "ОФП", "издръжливост"],
    coachingPoints: [
      "Поддържайте равномерно темпо (HR 130-140 bpm).",
      "Правилно дишане.",
      "Контролирана стойка и работа с ръцете.",
    ],
    intensity: 2,
    complexityLevel: 1,
  },
  {
    name: "Крос - 15 минути (Аеробна база)",
    description:
      "Равномерно бягане за изграждане на базова аеробна издръжливост, препоръчано от официалните мануали за предварителна подготовка на BWF.",
    category: "physical",
    source: "BWF Coach Level 1",
    location: ["outdoor"],
    ageGroups: ["U13", "U15", "U17", "U19", "Мъже и Жени"],
    durationMinutes: 15,
    equipment: "Спортен екип, Хронометър",
    focusTags: ["лагер", "ОФП", "издръжливост"],
    coachingPoints: [
      "Постепенно увеличаване на темпото през последните 3 минути.",
      "Фокус върху ритъма на бягане.",
    ],
    intensity: 3,
    complexityLevel: 1,
  },
  {
    name: "Крос - 20 минути (Стандартна аеробна подготовка)",
    description:
      "Стандартен крос за изграждане на кардиоваскуларен капацитет, типичен за предсезонни лагери (Badminton Asia).",
    category: "physical",
    source: "Badminton Asia / BWF Coach Level 2",
    location: ["outdoor"],
    ageGroups: ["U15", "U17", "U19", "Мъже и Жени"],
    durationMinutes: 20,
    equipment: "Спортен екип, Хронометър",
    focusTags: ["лагер", "ОФП", "издръжливост", "сърдечно-съдова подготовка"],
    coachingPoints: [
      "Темпото трябва да е предизвикателно, но поддържано без спиране.",
      "Ментален фокус и преодоляване на първоначалната умора.",
    ],
    intensity: 4,
    complexityLevel: 1,
  },
  {
    name: "Крос - 30 минути (Развитие на дълбока издръжливост)",
    description:
      "Дълго аеробно натоварване, ключово за елитни състезатели по време на тежки интензивни лагери за натрупване на обем.",
    category: "physical",
    source: "Badminton Europe Centre of Excellence",
    location: ["outdoor"],
    ageGroups: ["U17", "U19", "Мъже и Жени"],
    durationMinutes: 30,
    equipment: "Спортен екип, Хронометър, Монитор за сърдечен ритъм (опция)",
    focusTags: ["лагер", "ОФП", "издръжливост", "ментика"],
    coachingPoints: [
      "Разпределяне на силите равномерно през целите 30 минути.",
      "Психологическа устойчивост.",
      "HR в зона 3 (70-80% от Max HR).",
    ],
    intensity: 5,
    complexityLevel: 2,
  },
  // HILL SPRINTS & INTERVALS
  {
    name: "Спринтове по наклон (Hill Sprints)",
    description:
      "Развитие на експлозивна сила в краката и анаеробна издръжливост. Класическо упражнение в азиатската школа (Индонезия, Малайзия) за лагерна подготовка.",
    category: "physical",
    source: "BWF Coach Level 2 / Asian Badminton Training Systems",
    location: ["outdoor"],
    ageGroups: ["U15", "U17", "U19", "Мъже и Жени"],
    durationMinutes: 15,
    equipment: "Терен с наклон (хълм)",
    focusTags: ["лагер", "ОФП", "експлозивна сила", "анаеробна издръжливост"],
    coachingPoints: [
      "Високо повдигане на коленете.",
      "Мощна работа с ръцете.",
      "Пълен спринт нагоре, бавно връщане надолу за възстановяване.",
    ],
    intensity: 5,
    complexityLevel: 2,
    defaultSets: 10,
    defaultWorkSec: 15,
    defaultRestSec: 45,
  },
  {
    name: "Интервални отсечки (Interval Runs) - 400m",
    description:
      "Развиване на лактатна толерантност и способност за поддържане на високо темпо. Популярно в европейската школа.",
    category: "physical",
    source: "Badminton Europe Training Manual",
    location: ["outdoor", "both"],
    ageGroups: ["U17", "U19", "Мъже и Жени"],
    durationMinutes: 20,
    equipment: "Лекоатлетическа писта или измерено разстояние, Хронометър",
    focusTags: ["лагер", "ОФП", "лактатна толерантност", "интервали"],
    coachingPoints: [
      "Задаване на целево време за 400м (напр. 1:15 - 1:30 мин).",
      "Строго спазване на времето за почивка.",
    ],
    intensity: 5,
    complexityLevel: 2,
    defaultSets: 6,
    defaultWorkSec: 90,
    defaultRestSec: 90,
  },
  // SAND/OUTDOOR AGILITY
  {
    name: "Shadow Badminton (Footwork) на пясък",
    description:
      "Придвижване по корта без перо, изпълнявано на пясък или мека трева. Увеличава съпротивлението и заздравява ставите (популярно в датската и индонезийската школи на лагери).",
    category: "technical",
    source: "BWF Coach Level 2 / Danish Badminton Camps",
    location: ["outdoor"],
    ageGroups: ["U15", "U17", "U19", "Мъже и Жени"],
    durationMinutes: 15,
    equipment: "Пясъчник или плаж, Ракета",
    phase: "main-tech",
    focusTags: ["лагер", "специфична сила", "footwork"],
    coachingPoints: [
      "Фокус върху баланса, тъй като пясъкът нарушава стабилността.",
      "По-широка основа и по-мощно изтласкване.",
      "Поддържане на правилна техника на удара въпреки тежкия терен.",
    ],
    intensity: 4,
    complexityLevel: 3,
    defaultSets: 6,
    defaultWorkSec: 45,
    defaultRestSec: 45,
  },
  {
    name: "Плиометрия на открито (Jump Circuit)",
    description:
      "Серия от подскоци (жабешки, на един крак, скок от клек) за експлозивност и отскок за смач. Част от ОФП модула на BWF.",
    category: "physical",
    source: "BWF Coach Level 1 & 2",
    location: ["outdoor", "both"],
    ageGroups: ["U13", "U15", "U17", "U19", "Мъже и Жени"],
    durationMinutes: 15,
    equipment: "Конуси, Препятствия (опция)",
    focusTags: ["лагер", "ОФП", "експлозивност", "скок"],
    coachingPoints: [
      "Меко приземяване (абсорбиране на шока от коленете).",
      "Минимално време за контакт със земята (reactive jumps).",
      "Коректна стойка на тялото във въздуха.",
    ],
    intensity: 4,
    complexityLevel: 3,
  },
  {
    name: "Кръгова тренировка за Core стабилност",
    description:
      "Основа за трансфер на сила и превенция от контузии при дълги лагери. Упражнения като планк, руско усукване, повдигане на крака.",
    category: "physical",
    source: "Badminton Europe Centre of Excellence",
    location: ["outdoor", "both"],
    ageGroups: ["U11", "U13", "U15", "U17", "U19", "Мъже и Жени"],
    durationMinutes: 15,
    equipment: "Постелки",
    focusTags: ["лагер", "ОФП", "core", "превенция"],
    coachingPoints: [
      "Поддържане на перфектна форма на гръбначния стълб.",
      "Качество над количество.",
    ],
    intensity: 3,
    complexityLevel: 2,
    defaultSets: 4,
    defaultWorkSec: 40,
    defaultRestSec: 20,
  },
  // NEW ADDITIONS
  {
    name: "Стълбичка за координация (Agility Ladder)",
    description:
      "Развитие на бързи крака, координация и пъргавина. Използва се ежедневно в лагерите на Badminton Asia за развиване на невромускулната връзка.",
    category: "physical",
    source: "Badminton Asia Training Systems",
    location: ["outdoor", "both"],
    ageGroups: ["U9", "U11", "U13", "U15", "U17", "U19", "Мъже и Жени"],
    durationMinutes: 15,
    equipment: "Тренировъчна стълбичка",
    focusTags: ["лагер", "ОФП", "координация", "бързина"],
    coachingPoints: [
      "Работа на пръсти, петите не докосват земята.",
      "Погледът е напред, не надолу към краката.",
      "Синхронизирана работа на ръцете.",
    ],
    intensity: 3,
    complexityLevel: 3,
  },
  {
    name: "Shadow с жилетка с тежести (Weighted Vest Footwork)",
    description:
      "Придвижване по корта с допълнителна тежест (3-5 кг) за развиване на специфична сила в краката и експлозивност. Класика в китайската школа.",
    category: "technical",
    source: "Chinese Badminton Association Training Protocol",
    location: ["indoor", "both"],
    ageGroups: ["U15", "U17", "U19", "Мъже и Жени"],
    durationMinutes: 20,
    equipment: "Жилетка с тежести, Ракета",
    phase: "main-tech",
    focusTags: ["лагер", "специфична сила", "footwork"],
    coachingPoints: [
      "Стриктно спазване на техниката, за да се избегнат контузии в коленете.",
      "Дълбоки напади с контрол на тежестта.",
      "След сваляне на жилетката, направете 2 серии без нея за усещане на скоростта.",
    ],
    intensity: 5,
    complexityLevel: 4,
    defaultSets: 6,
    defaultWorkSec: 45,
    defaultRestSec: 60,
  },
  {
    name: "Хвърляне на медицинска топка (Medicine Ball Throws)",
    description:
      "Изграждане на rotational core strength и експлозивна сила за смач и бекхенд клиър. Често срещано в BWF Coach Level 2.",
    category: "physical",
    source: "BWF Coach Level 2",
    location: ["outdoor", "both"],
    ageGroups: ["U13", "U15", "U17", "U19", "Мъже и Жени"],
    durationMinutes: 15,
    equipment: "Медицинска топка (2-5 кг)",
    focusTags: ["лагер", "ОФП", "експлозивност", "core"],
    coachingPoints: [
      "Генериране на силата от краката и таза, не само от ръцете.",
      "Имитиране на движението при смач (хвърляне над глава).",
      "Странични усуквания за бекхенд/форхенд защита.",
    ],
    intensity: 4,
    complexityLevel: 2,
    defaultSets: 4,
    defaultWorkSec: 30,
    defaultRestSec: 30,
  },
  {
    name: "Beep Test (Тест на совалката)",
    description:
      "Мулти-етапен фитнес тест (20м совалка) за измерване и трениране на максималната кислородна консумация (VO2 Max). Задължителен тест на всички европейски и световни лагери.",
    category: "physical",
    source: "Badminton Europe / BWF",
    location: ["indoor", "both"],
    ageGroups: ["U13", "U15", "U17", "U19", "Мъже и Жени"],
    durationMinutes: 20,
    equipment: "Конуси (20м разстояние), Аудио запис за Beep Test, Колонка",
    focusTags: ["лагер", "ОФП", "тестуване", "VO2 Max", "издръжливост"],
    coachingPoints: [
      "Икономично бягане в ранните етапи.",
      "Рязко спиране и обръщане на линията, за да се пести време.",
      "Максимално раздаване до пълен отказ.",
    ],
    intensity: 5,
    complexityLevel: 1,
  },
  {
    name: "Много пера защита на пясък (Multi-shuttle Defense on Sand)",
    description:
      "Подаване на много пера (смачове/драйвове) към състезател, който е стъпил в пясъчник. Уникално упражнение за бързи рефлекси и тежки крака (Малайзийска школа).",
    category: "technical",
    source: "Badminton Association of Malaysia (BAM)",
    location: ["outdoor"],
    ageGroups: ["U15", "U17", "U19", "Мъже и Жени"],
    durationMinutes: 15,
    equipment: "Пясъчник, Мрежа на открито, Кош с пера",
    phase: "main-tech",
    focusTags: ["лагер", "защита", "мулти-пера", "рефлекси"],
    coachingPoints: [
      "Много нисък център на тежестта.",
      "Използване предимно на пръсти и китка, тъй като краката са 'заключени' в пясъка.",
      "Развитие на паник-защита и стабилност на рамото.",
    ],
    intensity: 5,
    complexityLevel: 4,
    defaultSets: 8,
    defaultWorkSec: 20,
    defaultRestSec: 40,
  },
];
