import { Exercise } from "@/types/planner.types";

export const TECHNICAL_EXERCISES_PART2: Omit<
  Exercise,
  "id" | "siteId" | "createdAt" | "updatedAt"
>[] = [
  {
    name: "Драйв Защита (Drive Defense)",
    description:
      "Връщане на смаш не с къс блок, а със силен плосък драйв по диагонал. Целта е да се премине от защита директно в атака.",
    category: "technical",
    phase: "main-tech",
    focusTags: ["Защита"],
    complexityLevel: 5,
    intensity: 3,
    source: "Badminton Asia",
    location: ["indoor"],
    ageGroups: ["U15", "U17", "U19", "Мъже и Жени"],
    durationMinutes: 15,
    equipment: "Кош с пера",
    videoUrl:
      "https://www.youtube.com/results?search_query=badminton+drive+defense+technique",
  },
  {
    name: "Lift от мрежа по диагонал (Cross-court Net Lift)",
    description:
      "Много труден удар от предна линия, при който перото се изчиства дълбоко назад по диагонал. Изисква силна китка и скриване на удара.",
    category: "technical",
    phase: "main-tech",
    focusTags: ["Мрежа"],
    complexityLevel: 5,
    intensity: 3,
    source: "BWF Level 3",
    location: ["indoor"],
    ageGroups: ["U15", "U17", "U19", "Мъже и Жени"],
    durationMinutes: 15,
    equipment: "Пера",
    videoUrl:
      "https://www.youtube.com/results?search_query=badminton+cross+court+net+lift",
  },
  {
    name: "Push Shot от бекхенд (Backhand Push)",
    description:
      "На мрежата, вместо мек удар (net shot), играчът избутва перото бързо и плоско към средната зона на корта на противника.",
    category: "technical",
    phase: "main-tech",
    focusTags: ["Обща Подготовка"],
    complexityLevel: 3,
    intensity: 3,
    source: "Badminton Europe",
    location: ["indoor"],
    ageGroups: ["U13", "U15", "U17", "U19", "Мъже и Жени"],
    durationMinutes: 10,
    equipment: "Пера",
    videoUrl:
      "https://www.youtube.com/results?search_query=badminton+backhand+push+technique",
  },
  {
    name: "Brush Net Shot",
    description:
      "Техника на мрежата, при която ракетата 'изчетква' перото отстрани, за да го завърти агресивно около оста му.",
    category: "technical",
    phase: "main-tech",
    focusTags: ["Мрежа"],
    complexityLevel: 5,
    intensity: 3,
    source: "BWF High Performance",
    location: ["indoor"],
    ageGroups: ["U15", "U17", "U19", "Мъже и Жени"],
    durationMinutes: 15,
    equipment: "Пера",
    videoUrl:
      "https://www.youtube.com/results?search_query=badminton+brush+net+shot+tumbling",
  },
  {
    name: "Хват за двойки (Panhandle Grip)",
    description:
      "Тренировка на специфичния хват тип 'тиган', използван за убиване на пера (Net kill) и бързи драйвове над мрежата.",
    category: "technical",
    phase: "main-tech",
    focusTags: ["Двойки"],
    complexityLevel: 3,
    intensity: 3,
    source: "Национални методики",
    location: ["indoor"],
    ageGroups: ["U13", "U15", "U17", "U19", "Мъже и Жени"],
    durationMinutes: 10,
    equipment: "Ракета",
    videoUrl:
      "https://www.youtube.com/results?search_query=badminton+panhandle+grip+net+kill",
  },
  {
    name: "Clear с атакуваща траектория (Attacking Clear)",
    description:
      "Изчистване, което не е високо, а много плоско и бързо. Цели да прехвърли противника, преди той да успее да реагира.",
    category: "technical",
    phase: "main-tech",
    focusTags: ["Clear"],
    complexityLevel: 5,
    intensity: 3,
    source: "BWF Level 2",
    location: ["indoor"],
    ageGroups: ["U15", "U17", "U19", "Мъже и Жени"],
    durationMinutes: 15,
    equipment: "Пера",
    videoUrl:
      "https://www.youtube.com/results?search_query=badminton+attacking+clear+technique",
  },
  {
    name: "Лъжлив Drop Shot (Hold and Drop)",
    description:
      "Играчът замахва и спира ракетата за част от секундата (hold), след което леко пуска перото (drop), докато противникът вече е тръгнал назад.",
    category: "technical",
    phase: "main-tech",
    focusTags: ["Drop"],
    complexityLevel: 5,
    intensity: 3,
    source: "Badminton Asia",
    location: ["indoor"],
    ageGroups: ["U15", "U17", "U19", "Мъже и Жени"],
    durationMinutes: 20,
    equipment: "Пера",
    videoUrl:
      "https://www.youtube.com/results?search_query=badminton+deceptive+hold+drop+shot",
  },
  {
    name: "Драйв от бекхенд (Backhand Drive)",
    description:
      "Плосък и силен удар от бекхенд страната, изпълняван само с предмишница и палец (thumb grip).",
    category: "technical",
    phase: "main-tech",
    focusTags: ["Обща Подготовка"],
    complexityLevel: 3,
    intensity: 3,
    source: "Badminton Europe",
    location: ["indoor"],
    ageGroups: ["U13", "U15", "U17", "U19", "Мъже и Жени"],
    durationMinutes: 15,
    equipment: "Пера",
    videoUrl:
      "https://www.youtube.com/results?search_query=badminton+backhand+drive+technique",
  },
  {
    name: "Плъзгане към мрежата (Chassé Steps)",
    description:
      "Специфични стъпки (приплъзване), при които единият крак догонва другия. Използват се за бързо стигане до мрежата.",
    category: "technical",
    phase: "main-tech",
    focusTags: ["Мрежа"],
    complexityLevel: 1,
    intensity: 3,
    source: "BWF Shuttle Time",
    location: ["indoor"],
    ageGroups: ["U9", "U11", "U13", "U15"],
    durationMinutes: 15,
    equipment: "Корт",
    videoUrl:
      "https://www.youtube.com/results?search_query=badminton+chasse+steps+footwork",
  },
  {
    name: "Защита между краката (Tweener - Trick shot)",
    description:
      "Забавно, но понякога спасяващо упражнение за напреднали: връщане на перото между краката, когато е минало зад играча.",
    category: "technical",
    phase: "main-tech",
    focusTags: ["Защита"],
    complexityLevel: 5,
    intensity: 3,
    source: "Trick Shots",
    location: ["indoor"],
    ageGroups: ["U17", "U19", "Мъже и Жени"],
    durationMinutes: 10,
    equipment: "Пера",
    videoUrl:
      "https://www.youtube.com/results?search_query=badminton+tweener+between+the+legs",
  },
  {
    name: "Смеш със завъртане на тялото (Full Body Rotation Smash)",
    description:
      "Обучение за използване на пълния торк на тялото: завъртане на таза, после рамото, после ръката. Изгражда най-мощния удар.",
    category: "technical",
    phase: "main-tech",
    focusTags: ["Smash"],
    complexityLevel: 5,
    intensity: 3,
    source: "Спортна физиология",
    location: ["indoor"],
    ageGroups: ["U15", "U17", "U19", "Мъже и Жени"],
    durationMinutes: 20,
    equipment: "Пера",
    videoUrl:
      "https://www.youtube.com/results?search_query=badminton+smash+body+rotation+kinetic+chain",
  },
  {
    name: "Улов на перото (Catching the Shuttle)",
    description:
      "Упражнение за усет към перото - играчът трябва да 'хване' падащо перо с ракетата си, без то да отскочи. Изисква много мека китка.",
    category: "technical",
    phase: "main-tech",
    focusTags: ["Обща Подготовка"],
    complexityLevel: 1,
    intensity: 3,
    source: "BWF Level 1",
    location: ["indoor"],
    ageGroups: ["U11", "U13", "U15", "U17"],
    durationMinutes: 10,
    equipment: "Ракета, перо",
    videoUrl:
      "https://www.youtube.com/results?search_query=badminton+catching+shuttle+with+racket",
  },
  {
    name: "Полу-смаш (Half Smash)",
    description:
      "Смаш, който е със същата техника, но се изпълнява с 50% сила. Цели да бъде по-точен и стръмен, вместо мощен.",
    category: "technical",
    phase: "main-tech",
    focusTags: ["Smash"],
    complexityLevel: 5,
    intensity: 3,
    source: "BWF High Performance",
    location: ["indoor"],
    ageGroups: ["U15", "U17", "U19", "Мъже и Жени"],
    durationMinutes: 15,
    equipment: "Пера",
    videoUrl:
      "https://www.youtube.com/results?search_query=badminton+half+smash+technique",
  },
  {
    name: "Къс сервис за сингъл (Short Serve Singles)",
    description:
      "За разлика от двойките, тук се играе малко по-далеч от линията и перото трябва да падне перфектно върху предната сервизна линия.",
    category: "technical",
    phase: "main-tech",
    focusTags: ["Сингъл"],
    complexityLevel: 3,
    intensity: 3,
    source: "Badminton Europe",
    location: ["indoor"],
    ageGroups: ["U13", "U15", "U17", "U19", "Мъже и Жени"],
    durationMinutes: 10,
    equipment: "Мишени",
    videoUrl:
      "https://www.youtube.com/results?search_query=badminton+short+serve+singles",
  },
  {
    name: "Return of Serve (Ретурн на къс сервис)",
    description:
      "Техника за тръгване максимално бързо напред веднага след сервиса на противника. Включва ранен контакт с перото.",
    category: "technical",
    phase: "main-tech",
    focusTags: ["Обща Подготовка"],
    complexityLevel: 5,
    intensity: 3,
    source: "BWF Doubles Specific",
    location: ["indoor"],
    ageGroups: ["U15", "U17", "U19", "Мъже и Жени"],
    durationMinutes: 15,
    equipment: "Пера",
    videoUrl:
      "https://www.youtube.com/results?search_query=badminton+doubles+return+of+serve",
  },
  {
    name: "Отблъскване от мрежата (Recovery from Net)",
    description:
      "След изпадане напред и удар на мрежата, енергично отблъскване с водещия (десен) крак назад към центъра.",
    category: "technical",
    phase: "main-tech",
    focusTags: ["Мрежа"],
    complexityLevel: 3,
    intensity: 3,
    source: "Национални методики",
    location: ["indoor"],
    ageGroups: ["U13", "U15", "U17", "U19", "Мъже и Жени"],
    durationMinutes: 15,
    equipment: "Корт",
    videoUrl:
      "https://www.youtube.com/results?search_query=badminton+net+recovery+footwork",
  },
  {
    name: "Бекхенд Смаш (Backhand Smash)",
    description:
      "Много рядък и труден удар за напреднали. Изпълнява се с рязко камшично движение от бекхенд, когато играчът е закъснял.",
    category: "technical",
    phase: "main-tech",
    focusTags: ["Smash"],
    complexityLevel: 5,
    intensity: 3,
    source: "Badminton Asia",
    location: ["indoor"],
    ageGroups: ["U19", "Мъже и Жени"],
    durationMinutes: 10,
    equipment: "Пера",
    videoUrl:
      "https://www.youtube.com/results?search_query=badminton+backhand+smash+technique",
  },
  {
    name: "Flat Clear (Плосък Клиър)",
    description:
      "Изчистване на перото, което лети малко над ракетата на противника. Много по-атакуващо от нормалния висок клиър.",
    category: "technical",
    phase: "main-tech",
    focusTags: ["Clear"],
    complexityLevel: 5,
    intensity: 3,
    source: "BWF Level 3",
    location: ["indoor"],
    ageGroups: ["U15", "U17", "U19", "Мъже и Жени"],
    durationMinutes: 15,
    equipment: "Пера",
    videoUrl:
      "https://www.youtube.com/results?search_query=badminton+flat+clear+punch+clear",
  },
  {
    name: "Late Net Shot (Закъснял удар на мрежата)",
    description:
      "Играчът стига до перото много късно (на сантиметри от пода). Целта е с много фино движение да се прехвърли филето.",
    category: "technical",
    phase: "main-tech",
    focusTags: ["Мрежа"],
    complexityLevel: 5,
    intensity: 3,
    source: "Спортна физиология",
    location: ["indoor"],
    ageGroups: ["U15", "U17", "U19", "Мъже и Жени"],
    durationMinutes: 15,
    equipment: "Кош с пера",
    videoUrl:
      "https://www.youtube.com/results?search_query=badminton+late+net+shot+recovery",
  },
  {
    name: "Драйв Сервис (Drive Serve)",
    description:
      "Сервис, който се изпълнява силно и плоско, директно към лицето или гърдите на посрещащия. Често използван елемент на изненада.",
    category: "technical",
    phase: "main-tech",
    focusTags: ["Обща Подготовка"],
    complexityLevel: 5,
    intensity: 3,
    source: "Badminton Europe",
    location: ["indoor"],
    ageGroups: ["U15", "U17", "U19", "Мъже и Жени"],
    durationMinutes: 10,
    equipment: "Пера",
    videoUrl:
      "https://www.youtube.com/results?search_query=badminton+drive+flick+serve",
  },
  {
    name: "Around the Head Drop (Около главата - Дроп)",
    description:
      "Удар от бекхенд страната, но изпълнен с форхенд хват и огъване на тялото (китайски скок), завършващ с рязък дроп по правата.",
    category: "technical",
    phase: "main-tech",
    focusTags: ["Drop"],
    complexityLevel: 5,
    intensity: 3,
    source: "BWF High Performance",
    location: ["indoor"],
    ageGroups: ["U15", "U17", "U19", "Мъже и Жени"],
    durationMinutes: 15,
    equipment: "Пера",
    videoUrl:
      "https://www.youtube.com/results?search_query=badminton+round+the+head+drop+shot",
  },
  {
    name: "Split Step (Основа на движението)",
    description:
      "Малък подскок (разтваряне на краката), който се прави в точния момент, когато противникът удря перото. Най-важният технически елемент за бързина.",
    category: "technical",
    phase: "main-tech",
    focusTags: ["Обща Подготовка"],
    complexityLevel: 1,
    intensity: 3,
    source: "Национални методики",
    location: ["indoor"],
    ageGroups: ["U9", "U11", "U13", "U15", "U17", "U19", "Мъже и Жени"],
    durationMinutes: 20,
    equipment: "Корт",
    videoUrl:
      "https://www.youtube.com/results?search_query=badminton+split+step+timing",
  },
  {
    name: "Оттласкване от задния ъгъл (Recovery from Rear Court)",
    description:
      "След изпълнение на Smash или Clear, първата стъпка назад към центъра (Scissors kick recovery).",
    category: "technical",
    phase: "main-tech",
    focusTags: ["Обща Подготовка"],
    complexityLevel: 3,
    intensity: 3,
    source: "BWF Level 2",
    location: ["indoor"],
    ageGroups: ["U13", "U15", "U17", "U19", "Мъже и Жени"],
    durationMinutes: 15,
    equipment: "Корт",
    videoUrl:
      "https://www.youtube.com/results?search_query=badminton+scissor+kick+recovery",
  },
  {
    name: "Defensive Block (Мек блок от защита)",
    description:
      "Блокиране на силен смаш с цел перото да падне веднага зад мрежата. Изисква отпускане на китката в момента на удара.",
    category: "technical",
    phase: "main-tech",
    focusTags: ["Защита"],
    complexityLevel: 5,
    intensity: 3,
    source: "Badminton Asia",
    location: ["indoor"],
    ageGroups: ["U15", "U17", "U19", "Мъже и Жени"],
    durationMinutes: 15,
    equipment: "Пера",
    videoUrl:
      "https://www.youtube.com/results?search_query=badminton+soft+defense+block",
  },
  {
    name: "Grip Tightening (Стискане на хвата)",
    description:
      "Упражнение за контрол: ракетата се държи отпуснато и се стиска силно само в милисекундата на удара. Генерира максимална скорост на главата на ракетата.",
    category: "technical",
    phase: "main-tech",
    focusTags: ["Обща Подготовка"],
    complexityLevel: 5,
    intensity: 3,
    source: "Спортна физиология",
    location: ["indoor"],
    ageGroups: ["U15", "U17", "U19", "Мъже и Жени"],
    durationMinutes: 10,
    equipment: "Ракета",
    videoUrl:
      "https://www.youtube.com/results?search_query=badminton+grip+tightening+power",
  },
];
