import { Exercise } from "@/types/planner.types";

export const WARMUP_EXERCISES: Omit<
  Exercise,
  "id" | "siteId" | "createdAt" | "updatedAt"
>[] = [
  {
    name: "Динамичен стречинг и мобилност (BWF Standard)",
    description:
      "Стандартен протокол за загрявка на BWF. Включва: 1. Леко бягане 3 мин. 2. Ротации на ставите (врата, рамене, китки, таз, глезени). 3. Динамични разтягания (високо коляно, пети към седалището, странични напади, 'crossover' бягане). 4. Спринтове на къси дистанции (5-10 метра) с постепенно увеличаване на скоростта.",
    category: "warmup",
    phase: "warmup",
    focusTags: ["Обща Подготовка"],
    complexityLevel: 1,
    intensity: 2,
    source: "BWF Coach Education Manual Level 1",
    location: ["both"],
    ageGroups: ["U9", "U11", "U13", "U15", "U17", "U19", "Мъже и Жени"],
    durationMinutes: 15,
    equipment: "Няма",
  },
  {
    name: "Специфична бадминтон загрявка с перо (Shadow & Tap)",
    description:
      "Специфична загрявка преди мач или техническа тренировка. Започва със 'Shadow Badminton' (имитация на удари без перо) с акцент върху работата на краката (Footwork). Следват 5 минути леко подаване (Drives & Clears) в центъра на корта, постепенно преминавайки към по-широки ъгли.",
    category: "warmup",
    phase: "warmup",
    focusTags: ["Обща Подготовка"],
    complexityLevel: 1,
    intensity: 2,
    source: "Badminton Europe Pre-Match Protocol",
    location: ["indoor"],
    ageGroups: ["U9", "U11", "U13", "U15", "U17", "U19", "Мъже и Жени"],
    durationMinutes: 10,
    equipment: "Ракети, Пера",
  },
  {
    name: "Agility Ladder Warm-up (Координационна стълба)",
    description:
      "Използване на координационна стълба за загрявка на нервната система и подобряване на бързината на краката. Упражнения: 'One in, one out', 'Two in, two out', 'Icky Shuffle', 'Lateral runs'. Всяко упражнение се повтаря по 2 пъти с плавно увеличаване на темпото.",
    category: "warmup",
    phase: "warmup",
    focusTags: ["Обща Подготовка"],
    complexityLevel: 1,
    intensity: 2,
    source: "Badminton Asia Fundamentals",
    location: ["both"],
    ageGroups: ["U9", "U11", "U13", "U15", "U17", "U19", "Мъже и Жени"],
    durationMinutes: 10,
    equipment: "Координационна стълбичка",
  },
  {
    name: "Реакционна загрявка (Reaction Games)",
    description:
      "Игри за реакция, подходящи за всички възрасти за 'събуждане' на състезателите. Треньорът посочва посока или цвят на конус, а състезателите трябва да реагират със сплит-степ (split-step) и спринт до съответната точка. Включва и игра на двойки: 'Докосни коляното на партньора' (Tag games) за загрявка на краката и торса.",
    category: "warmup",
    phase: "warmup",
    focusTags: ["Обща Подготовка"],
    complexityLevel: 1,
    intensity: 2,
    source: "BWF Shuttle Time Programme",
    location: ["indoor"],
    ageGroups: ["U9", "U11", "U13", "U15", "U17", "U19", "Мъже и Жени"],
    durationMinutes: 8,
    equipment: "Цветни конуси",
  },
  {
    name: "Загрявка със съпротивителни ластици (Theraband Activation)",
    description:
      "Протокол за активация на ротаторния маншон и мускулите около раменната става. Включва външна и вътрешна ротация с лек ластик (15 повторения), симулация на удар над глава срещу съпротивление и издърпване към гърдите (Face pulls).",
    category: "warmup",
    phase: "warmup",
    focusTags: ["Обща Подготовка"],
    complexityLevel: 3,
    intensity: 2,
    source: "BWF Sports Science & Medicine",
    location: ["both"],
    ageGroups: ["U13", "U15", "U17", "U19", "Мъже и Жени"],
    durationMinutes: 7,
    equipment: "Съпротивителни ластици (Theraband)",
  },
  // --- Нови 30 упражнения за загрявка ---
  {
    name: "Лек крос с промяна на посоката",
    description:
      "Свободно бягане около корта за 3 минути. При сигнал от треньора (свирка или пляскане), състезателите променят посоката си на бягане на 180 градуса, използвайки бърз сплит-степ и рязко оттласкване.",
    category: "warmup",
    phase: "warmup",
    focusTags: ["Обща Подготовка"],
    complexityLevel: 1,
    intensity: 2,
    source: "Badminton Europe Training Manual",
    location: ["indoor", "outdoor"],
    ageGroups: ["U9", "U11", "U13", "U15", "U17", "U19", "Мъже и Жени"],
    durationMinutes: 5,
    equipment: "Няма",
  },
  {
    name: "Загрявка на китки и предмишници (Figure 8)",
    description:
      "Държейки ракетата, състезателят описва във въздуха цифрата '8' (Figure 8) само с движение на китката и предмишницата. Упражнението се изпълнява по 30 секунди за форхенд и бекхенд хват, като постепенно се увеличава скоростта.",
    category: "warmup",
    phase: "warmup",
    focusTags: ["Обща Подготовка"],
    complexityLevel: 1,
    intensity: 2,
    source: "Badminton Asia Technical Drills",
    location: ["indoor"],
    ageGroups: ["U9", "U11", "U13", "U15", "U17", "U19", "Мъже и Жени"],
    durationMinutes: 3,
    equipment: "Ракети",
  },
  {
    name: "Сянка с тежка ракета (Heavy Racket Shadow)",
    description:
      "Изпълняване на основни бадминтон движения (clears, drops, smashes) с помощта на тренировъчна тежка ракета или калъф, поставен върху ракетата. Загрява специфичните мускули на рамото и гърба, като същевременно помага за тайминга.",
    category: "warmup",
    phase: "warmup",
    focusTags: ["Обща Подготовка"],
    complexityLevel: 3,
    intensity: 2,
    source: "BWF Advanced Coaching",
    location: ["indoor"],
    ageGroups: ["U13", "U15", "U17", "U19", "Мъже и Жени"],
    durationMinutes: 5,
    equipment: "Тежка ракета или калъф",
  },
  {
    name: "Огледална загрявка по двойки (Mirror Drill)",
    description:
      "Двама състезатели застават един срещу друг на 2 метра разстояние. Единият е 'лидер', а другият 'огледало'. Лидерът прави бързи бадминтон стъпки наляво, надясно, напред или назад. Огледалото трябва максимално бързо да повтори движението.",
    category: "warmup",
    phase: "warmup",
    focusTags: ["Обща Подготовка"],
    complexityLevel: 1,
    intensity: 2,
    source: "BWF Shuttle Time",
    location: ["indoor"],
    ageGroups: ["U9", "U11", "U13", "U15", "U17", "U19", "Мъже и Жени"],
    durationMinutes: 5,
    equipment: "Няма",
  },
  {
    name: "Гоненица (Catch/Tag) само със странични стъпки (Chassé)",
    description:
      "Класическа гоненица в рамките на едно игрище за бадминтон, но състезателите имат право да се придвижват само чрез приплъзване (странични бадминтон стъпки - Chassé). Чудесно за загряване на аддукторите.",
    category: "warmup",
    phase: "warmup",
    focusTags: ["Обща Подготовка"],
    complexityLevel: 1,
    intensity: 2,
    source: "Badminton Europe Kids Programme",
    location: ["indoor"],
    ageGroups: ["U9", "U11", "U13"],
    durationMinutes: 5,
    equipment: "Няма",
  },
  {
    name: "Изхвърляне и хващане на перо (Shuttle Toss & Catch)",
    description:
      "Състезателят подхвърля перо високо във въздуха, прави сплит-степ, имитира удар (shadow) и след това трябва да хване перото преди да падне на земята. Развива координацията око-ръка.",
    category: "warmup",
    phase: "warmup",
    focusTags: ["Обща Подготовка"],
    complexityLevel: 1,
    intensity: 2,
    source: "Badminton Asia Fundamentals",
    location: ["indoor"],
    ageGroups: ["U9", "U11", "U13", "U15", "U17", "U19", "Мъже и Жени"],
    durationMinutes: 5,
    equipment: "Пера",
  },
  {
    name: "Сгъване и разгъване (Caterpillar Walk / Inchworm)",
    description:
      "От стоеж състезателят се навежда напред, допира земята с ръце и 'ходи' с ръцете напред до позиция за лицева опора. След това краката с малки стъпки 'догонват' ръцете, без да се сгъват коленете. Загрява задното бедро, прасците и раменния пояс.",
    category: "warmup",
    phase: "warmup",
    focusTags: ["Обща Подготовка"],
    complexityLevel: 1,
    intensity: 2,
    source: "BWF Sports Science & Medicine",
    location: ["indoor", "outdoor"],
    ageGroups: ["U11", "U13", "U15", "U17", "U19", "Мъже и Жени"],
    durationMinutes: 5,
    equipment: "Няма",
  },
  {
    name: "Високо коляно с преминаване на препятствия",
    description:
      "Наредени ниски препятствия (hurdles) или конуси на разстояние 50 см едно от друго. Състезателите преминават с високо повдигане на коленете, стъпвайки бързо в празните пространства. Загрява бедрените сгъвачи.",
    category: "warmup",
    phase: "warmup",
    focusTags: ["Обща Подготовка"],
    complexityLevel: 1,
    intensity: 2,
    source: "Badminton Europe Physical Prep",
    location: ["indoor", "outdoor"],
    ageGroups: ["U9", "U11", "U13", "U15", "U17", "U19", "Мъже и Жени"],
    durationMinutes: 5,
    equipment: "Ниски препятствия / Конуси",
  },
  {
    name: "Ротации на торса с медицинска топка",
    description:
      "Загрявка на коремната преса и косите коремни мускули. Състезателите стоят гръб до гръб на разстояние една ръка и си подават лека медицинска топка (1-2 кг) чрез ротация на торса наляво и надясно.",
    category: "warmup",
    phase: "warmup",
    focusTags: ["Обща Подготовка"],
    complexityLevel: 3,
    intensity: 2,
    source: "BWF Advanced Level 2",
    location: ["indoor"],
    ageGroups: ["U13", "U15", "U17", "U19", "Мъже и Жени"],
    durationMinutes: 5,
    equipment: "Лека медицинска топка",
  },
  {
    name: "Кръстосани крачки (Grapevine / Carioca)",
    description:
      "Странично бягане, при което левият крак преминава последователно пред и зад десния крак (и обратно). Завърта се максимално таза, докато раменете остават успоредни на мрежата. Загрява тазобедрената става.",
    category: "warmup",
    phase: "warmup",
    focusTags: ["Обща Подготовка"],
    complexityLevel: 1,
    intensity: 2,
    source: "Badminton Asia Physical Base",
    location: ["indoor", "outdoor"],
    ageGroups: ["U9", "U11", "U13", "U15", "U17", "U19", "Мъже и Жени"],
    durationMinutes: 3,
    equipment: "Няма",
  },
  {
    name: "Загрявка 'Хвърляне на диск'",
    description:
      "Свободно движение на корта. Състезателят заема стабилен напад с ракетата в ръка и имитира движение на 'хвърляне на диск' или силно бекхенд изчистване, за да отвори гръдния кош и да загрее гърба.",
    category: "warmup",
    phase: "warmup",
    focusTags: ["Обща Подготовка"],
    complexityLevel: 1,
    intensity: 2,
    source: "BWF Coach Education",
    location: ["indoor"],
    ageGroups: ["U11", "U13", "U15", "U17", "U19", "Мъже и Жени"],
    durationMinutes: 3,
    equipment: "Ракети",
  },
  {
    name: "Shadow Footwork (Сянка) 6 ъгъла",
    description:
      "В центъра на корта. Треньорът показва посоки с ръка, а състезателите се придвижват към един от 6-те ъгъла на корта със специфични бадминтон стъпки, правят въображаем удар и се връщат бързо в центъра.",
    category: "warmup",
    phase: "warmup",
    focusTags: ["Обща Подготовка"],
    complexityLevel: 1,
    intensity: 2,
    source: "Badminton Europe Footwork Base",
    location: ["indoor"],
    ageGroups: ["U9", "U11", "U13", "U15", "U17", "U19", "Мъже и Жени"],
    durationMinutes: 5,
    equipment: "Няма",
  },
  {
    name: "Ритници със задни бедра към глутеуса (Butt Kicks)",
    description:
      "Бягане на място или леко придвижване напред, като петите се повдигат максимално високо назад, докосвайки седалището. Загрява задната част на бедрата (hamstrings).",
    category: "warmup",
    phase: "warmup",
    focusTags: ["Обща Подготовка"],
    complexityLevel: 1,
    intensity: 2,
    source: "BWF Physical Protocol",
    location: ["both"],
    ageGroups: ["U9", "U11", "U13", "U15", "U17", "U19", "Мъже и Жени"],
    durationMinutes: 3,
    equipment: "Няма",
  },
  {
    name: "Lunges (Напади) със завъртане",
    description:
      "Състезателят прави голяма крачка напред (напад) с десния крак, докато лявото коляно почти опира земята. След това завърта торса надясно (към предния крак). Повтаря се с левия крак.",
    category: "warmup",
    phase: "warmup",
    focusTags: ["Обща Подготовка"],
    complexityLevel: 1,
    intensity: 2,
    source: "Badminton Asia Mobility",
    location: ["both"],
    ageGroups: ["U11", "U13", "U15", "U17", "U19", "Мъже и Жени"],
    durationMinutes: 5,
    equipment: "Няма",
  },
  {
    name: "Докосване на мрежата със сплит-степ",
    description:
      "Редица от състезатели. Всеки тръгва от задната линия на корта, бяга напред, прави сплит-степ, докосва горния ръб на мрежата и се връща назад с бадминтон крачки (отстъпване назад).",
    category: "warmup",
    phase: "warmup",
    focusTags: ["Обща Подготовка"],
    complexityLevel: 1,
    intensity: 2,
    source: "BWF Movement Drills",
    location: ["indoor"],
    ageGroups: ["U9", "U11", "U13", "U15", "U17", "U19", "Мъже и Жени"],
    durationMinutes: 5,
    equipment: "Няма",
  },
  {
    name: "Баланс на един крак със затворени очи",
    description:
      "Загрявка на проприоцепцията и малките стабилизиращи мускули на глезена. Състезателят застава на един крак и затваря очи за 20 секунди. Сменя крака.",
    category: "warmup",
    phase: "warmup",
    focusTags: ["Обща Подготовка"],
    complexityLevel: 1,
    intensity: 2,
    source: "Badminton Europe Proprioception",
    location: ["both"],
    ageGroups: ["U11", "U13", "U15", "U17", "U19", "Мъже и Жени"],
    durationMinutes: 3,
    equipment: "Няма",
  },
  {
    name: "Вдигане на пера (Shuttle Pick-up)",
    description:
      "Разпръснати 20 пера в едното поле. Състезателят тръгва от центъра, прави напад (lunge), взима едно перо и го носи в кофа в центъра. Връща се за следващото. Активира бедрените мускули и специфичния напад.",
    category: "warmup",
    phase: "warmup",
    focusTags: ["Обща Подготовка"],
    complexityLevel: 1,
    intensity: 2,
    source: "Badminton Asia Junior Training",
    location: ["indoor"],
    ageGroups: ["U9", "U11", "U13", "U15", "U17", "U19", "Мъже и Жени"],
    durationMinutes: 5,
    equipment: "Пера",
  },
  {
    name: "Wall Drives (Загрявка на стена)",
    description:
      "Двама състезатели използват свободна стена в залата. Подават си пера срещу стената (drives), стараейки се да поддържат бързо темпо. Много добро за загрявка на китката, реакцията и предмишницата.",
    category: "warmup",
    phase: "warmup",
    focusTags: ["Обща Подготовка"],
    complexityLevel: 1,
    intensity: 2,
    source: "BWF Technical Manual",
    location: ["indoor"],
    ageGroups: ["U11", "U13", "U15", "U17", "U19", "Мъже и Жени"],
    durationMinutes: 5,
    equipment: "Ракети, Пера, Стена",
  },
  {
    name: "Скокове 'Звезда' (Jumping Jacks)",
    description:
      "Класическо аеробно упражнение за повишаване на пулса. От стоеж, състезателят скача, разтваряйки краката и вдигайки ръцете над главата, след което се връща в изходна позиция.",
    category: "warmup",
    phase: "warmup",
    focusTags: ["Обща Подготовка"],
    complexityLevel: 1,
    intensity: 2,
    source: "BWF Foundation",
    location: ["both"],
    ageGroups: ["U9", "U11", "U13", "U15", "U17", "U19", "Мъже и Жени"],
    durationMinutes: 3,
    equipment: "Няма",
  },
  {
    name: "Спайдърмен разтягане (Spiderman Stretch)",
    description:
      "От позиция за лицева опора, десният крак се изнася напред до дясната ръка. Тазът се спуска надолу, за да се разтегнат слабините и бедрата. Държи се 2-3 секунди, сменя се кракът.",
    category: "warmup",
    phase: "warmup",
    focusTags: ["Обща Подготовка"],
    complexityLevel: 3,
    intensity: 2,
    source: "Badminton Europe Dynamic Flex",
    location: ["both"],
    ageGroups: ["U13", "U15", "U17", "U19", "Мъже и Жени"],
    durationMinutes: 4,
    equipment: "Няма",
  },
  {
    name: "Arm Circles (Кръгове с ръце)",
    description:
      "Първо бавни, а после бързи кръгове с прави ръце напред, след това назад. Първо малки кръгове (от раменете), след това големи. Идеално за загряване на раменния пояс.",
    category: "warmup",
    phase: "warmup",
    focusTags: ["Обща Подготовка"],
    complexityLevel: 1,
    intensity: 2,
    source: "BWF Shuttle Time",
    location: ["both"],
    ageGroups: ["U9", "U11", "U13", "U15", "U17", "U19", "Мъже и Жени"],
    durationMinutes: 2,
    equipment: "Няма",
  },
  {
    name: "Side Shuffles с докосване на пода",
    description:
      "Състезателите се приплъзват странично (Chassé) по ширината на корта. На всяка странична линия се навеждат (с клякане, а не с прегъване на гърба) и докосват пода с ръка. Загрява коленете и страничните мускули.",
    category: "warmup",
    phase: "warmup",
    focusTags: ["Обща Подготовка"],
    complexityLevel: 1,
    intensity: 2,
    source: "Badminton Asia Fundamentals",
    location: ["both"],
    ageGroups: ["U9", "U11", "U13", "U15", "U17", "U19", "Мъже и Жени"],
    durationMinutes: 4,
    equipment: "Няма",
  },
  {
    name: "High Knees (Високи колене на място)",
    description:
      "Интензивно бягане на място с много високо повдигане на коленете към гърдите. Прави се в серии по 15-20 секунди за рязко покачване на сърдечния ритъм.",
    category: "warmup",
    phase: "warmup",
    focusTags: ["Обща Подготовка"],
    complexityLevel: 1,
    intensity: 2,
    source: "BWF Warm-up Protocols",
    location: ["both"],
    ageGroups: ["U9", "U11", "U13", "U15", "U17", "U19", "Мъже и Жени"],
    durationMinutes: 3,
    equipment: "Няма",
  },
  {
    name: "Подмятане на перо с ръка (Hand Shuttle Toss)",
    description:
      "Много добро за загрявка на очите. Двама души застават от двете страни на мрежата и си подават перо с ръка, опитвайки се да го хванат във въздуха и веднага да го върнат. Темпото постепенно се ускорява.",
    category: "warmup",
    phase: "warmup",
    focusTags: ["Обща Подготовка"],
    complexityLevel: 1,
    intensity: 2,
    source: "BWF Kids Level 1",
    location: ["indoor"],
    ageGroups: ["U9", "U11", "U13", "U15"],
    durationMinutes: 5,
    equipment: "Пера",
  },
  {
    name: "Загрявка на глезените (Ankle Rolls & Hops)",
    description:
      "Въртене на глезените във въздуха наляво и надясно. След това 30 секунди малки скокчета на един крак (Hops) напред и назад. Предпазва от изкълчвания на корта.",
    category: "warmup",
    phase: "warmup",
    focusTags: ["Обща Подготовка"],
    complexityLevel: 1,
    intensity: 2,
    source: "Badminton Europe Medical Commission",
    location: ["both"],
    ageGroups: ["U9", "U11", "U13", "U15", "U17", "U19", "Мъже и Жени"],
    durationMinutes: 4,
    equipment: "Няма",
  },
  {
    name: "Drive / Net Play с половина корт",
    description:
      "След базовия физически уормъп, двама състезатели застават пред сервис линията и играят само на мрежа (spin, tumble) или леки драйвове. Ракетите се държат късо. Загрява фината моторика и китката.",
    category: "warmup",
    phase: "warmup",
    focusTags: ["Обща Подготовка"],
    complexityLevel: 1,
    intensity: 2,
    source: "BWF Technical Warm-up",
    location: ["indoor"],
    ageGroups: ["U11", "U13", "U15", "U17", "U19", "Мъже и Жени"],
    durationMinutes: 5,
    equipment: "Ракети, Пера",
  },
  {
    name: "Спринтове с ластици (Resisted Sprints)",
    description:
      "Единият партньор държи съпротивителен ластик, обхващащ талията на другия. Вторият партньор се опитва да спринтира напред, преодолявайки съпротивлението. След 5-8 метра ластикът се отпуска за рязко ускорение.",
    category: "warmup",
    phase: "warmup",
    focusTags: ["Обща Подготовка"],
    complexityLevel: 5,
    intensity: 2,
    source: "Badminton Asia Advanced Conditioning",
    location: ["both"],
    ageGroups: ["U15", "U17", "U19", "Мъже и Жени"],
    durationMinutes: 6,
    equipment: "Съпротивителни ластици",
  },
  {
    name: "Разтягане тип 'Люлка' (Scorpion Stretch)",
    description:
      "Лег по очи. Единият крак се сгъва в коляното, повдига се и се прехвърля зад тялото, опитвайки се да докосне пода от противоположната страна. Загрява долната част на гърба и гърдите.",
    category: "warmup",
    phase: "warmup",
    focusTags: ["Обща Подготовка"],
    complexityLevel: 3,
    intensity: 2,
    source: "BWF Physical Training",
    location: ["both"],
    ageGroups: ["U13", "U15", "U17", "U19", "Мъже и Жени"],
    durationMinutes: 4,
    equipment: "Постелки / Мека настилка",
  },
  {
    name: "Хвърляне на пера с ракета (Shuttle Flicking)",
    description:
      "Състезателят поставя перо на земята, закача го с върха на ракетата (flick) и го изхвърля във въздуха, опитвайки се да го хване обратно или да го удари директно. Загрява чувството към ракетата (racket feel).",
    category: "warmup",
    phase: "warmup",
    focusTags: ["Обща Подготовка"],
    complexityLevel: 1,
    intensity: 2,
    source: "BWF Skill Acquisition",
    location: ["indoor"],
    ageGroups: ["U9", "U11", "U13", "U15", "U17", "U19", "Мъже и Жени"],
    durationMinutes: 3,
    equipment: "Ракети, Пера",
  },
  {
    name: "Загрявка на гърдите (Chest Expansions)",
    description:
      "Ръцете са изпънати напред, събрани. При вдишване ръцете се разтварят максимално назад, разтваряйки гръдния кош, след което се прибират. Прави се енергично за активация на гърба и гърдите.",
    category: "warmup",
    phase: "warmup",
    focusTags: ["Обща Подготовка"],
    complexityLevel: 1,
    intensity: 2,
    source: "Badminton Europe Dynamic Stretching",
    location: ["both"],
    ageGroups: ["U9", "U11", "U13", "U15", "U17", "U19", "Мъже и Жени"],
    durationMinutes: 2,
    equipment: "Няма",
  },
  {
    name: "Игри за баланс (Pushing hands)",
    description:
      "По двойки, състезателите застават един срещу друг с разтворени крака. Те трябва да се избутат само докосвайки дланите на партньора, опитвайки се да го накарат да загуби баланс и да мръдне крак.",
    category: "warmup",
    phase: "warmup",
    focusTags: ["Обща Подготовка"],
    complexityLevel: 1,
    intensity: 2,
    source: "BWF Coordination & Balance",
    location: ["both"],
    ageGroups: ["U9", "U11", "U13", "U15", "U17", "U19", "Мъже и Жени"],
    durationMinutes: 5,
    equipment: "Няма",
  },
  {
    name: "Clear до Clear (Full length warm-up)",
    description:
      "Подаване на високо и дълго перо (Clear) от крайна до крайна линия. Това е финалната фаза на бадминтон загрявката преди мач, за да се активира максималната мощност на рамото и гърба.",
    category: "warmup",
    phase: "warmup",
    focusTags: ["Обща Подготовка"],
    complexityLevel: 1,
    intensity: 2,
    source: "Badminton Asia Pre-Match",
    location: ["indoor"],
    ageGroups: ["U11", "U13", "U15", "U17", "U19", "Мъже и Жени"],
    durationMinutes: 5,
    equipment: "Ракети, Пера",
  },
  {
    name: "Загрявка на предното бедро (Quadriceps Walk)",
    description:
      "При всяка стъпка напред, състезателят хваща глезена на задния крак и леко издърпва петата към глутеуса, задържа 1 секунда, пуска и прави следващата стъпка с другия крак.",
    category: "warmup",
    phase: "warmup",
    focusTags: ["Обща Подготовка"],
    complexityLevel: 1,
    intensity: 2,
    source: "BWF Active Stretching",
    location: ["both"],
    ageGroups: ["U11", "U13", "U15", "U17", "U19", "Мъже и Жени"],
    durationMinutes: 3,
    equipment: "Няма",
  },
  {
    name: "Хеликоптер (Rotational Swings)",
    description:
      "С разтворени крака състезателят върти торса си наляво и надясно, оставяйки ръцете да се движат свободно и да 'удрят' леко тялото. Чудесно за разхлабване на лумбалната област.",
    category: "warmup",
    phase: "warmup",
    focusTags: ["Обща Подготовка"],
    complexityLevel: 1,
    intensity: 2,
    source: "Badminton Europe Mobility",
    location: ["both"],
    ageGroups: ["U9", "U11", "U13", "U15", "U17", "U19", "Мъже и Жени"],
    durationMinutes: 2,
    equipment: "Няма",
  },
  {
    name: "Бързи крачета (Fast Feet Drill)",
    description:
      "Позиция на лек клек. По сигнал състезателите започват да 'ситнят' с крака максимално бързо на място. При сигнал 'Спринт!', те спринтират 5 метра напред. Загрява бързите мускулни влакна.",
    category: "warmup",
    phase: "warmup",
    focusTags: ["Обща Подготовка"],
    complexityLevel: 1,
    intensity: 2,
    source: "BWF Agility Training",
    location: ["both"],
    ageGroups: ["U9", "U11", "U13", "U15", "U17", "U19", "Мъже и Жени"],
    durationMinutes: 4,
    equipment: "Няма",
  },
];
