
import { useState, useEffect } from 'react';
import { collection, addDoc, onSnapshot, query, orderBy, doc, updateDoc, deleteDoc, writeBatch, Timestamp } from 'firebase/firestore';
import { db } from '@/lib/firebase'; 
import { ScheduleEvent } from '@/types';

// A type for the new event, omitting the id which is generated by Firestore
type NewEvent = Omit<ScheduleEvent, 'id'>;

// Helper function to convert Firestore Timestamps to JS Date objects
const convertTimestamps = (data: any) => {
    const convertedData = { ...data };
    if (data.startDate && data.startDate instanceof Timestamp) {
        convertedData.startDate = data.startDate.toDate();
    }
    if (data.endDate && data.endDate instanceof Timestamp) {
        convertedData.endDate = data.endDate.toDate();
    }
    return convertedData;
};


export const useEvents = () => {
    const [events, setEvents] = useState<ScheduleEvent[]>([]);
    const [isLoading, setIsLoading] = useState(true);
    const [error, setError] = useState<Error | null>(null);

    useEffect(() => {
        setIsLoading(true);
        try {
            const eventsCollection = collection(db, 'events');
            const q = query(eventsCollection, orderBy('startDate', 'desc'));

            const unsubscribe = onSnapshot(q, (snapshot) => {
                const eventsData = snapshot.docs.map(doc => {
                    const data = doc.data();
                    const convertedData = convertTimestamps(data);
                    return {
                        id: doc.id,
                        ...convertedData,
                    } as ScheduleEvent;
                });
                setEvents(eventsData);
                setIsLoading(false);
            }, (err) => {
                console.error("Error fetching events:", err);
                setError(err);
                setIsLoading(false);
            });

            // Cleanup subscription on unmount
            return () => unsubscribe();

        } catch (err) {
            console.error("Error setting up snapshot listener:", err);
            setError(err as Error);
            setIsLoading(false);
        }
    }, []);

    const addEvent = async (event: NewEvent) => {
        if (!event.title || !event.type || !event.startDate) {
            throw new Error("Missing required event fields");
        }
        try {
            await addDoc(collection(db, 'events'), event);
        } catch (err) {
            console.error("Error adding event:", err);
            throw new Error("Failed to add event");
        }
    };
    
    const addMultipleEvents = async (events: NewEvent[]) => {
        const batch = writeBatch(db);
        const eventsCollection = collection(db, 'events');
        events.forEach(event => {
            const docRef = doc(eventsCollection);
            batch.set(docRef, event);
        });
        try {
            await batch.commit();
        } catch (err) {
            console.error("Error adding multiple events:", err);
            throw new Error("Failed to add multiple events");
        }
    };

    const updateEvent = async (eventId: string, eventData: Partial<NewEvent>) => {
        try {
            const eventRef = doc(db, 'events', eventId);
            await updateDoc(eventRef, eventData);
        } catch (err) {
            console.error("Error updating event:", err);
            throw new Error("Failed to update event");
        }
    };

    const deleteEvent = async (eventId: string) => {
        try {
            const eventRef = doc(db, 'events', eventId);
            await deleteDoc(eventRef);
        } catch (err) {
            console.error("Error deleting event:", err);
            throw new Error("Failed to delete event");
        }
    };
    
    const updateAttendees = async (eventId: string, attendeeIds: string[]) => {
        try {
            const eventRef = doc(db, 'events', eventId);
            await updateDoc(eventRef, { attendees: attendeeIds });
        } catch (err) {
            console.error("Error updating attendees:", err);
            throw new Error("Failed to update attendees");
        }
    };

    return { events, addEvent, addMultipleEvents, updateEvent, deleteEvent, updateAttendees, isLoading, error };
};
