name: Semgrep SAST

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  semgrep:
    name: Scan
    runs-on: ubuntu-latest
    container:
      image: semgrep/semgrep
    steps:
      - uses: actions/checkout@fbc6f3992d24b796d5a048ff273f7fcc4a7b6c09 # v5
      - run: semgrep scan --config auto --error
